# Econofísica y entropía en sistemas urbanos / regionales dinámicamente complejos {-}

Desde al menos los primeros esfuerzos de Alan Wilson (1967, 1970), la idea de utilizar la ley de la entropía para ayudar a modelar el desarrollo de patrones estructurales espaciales urbanos y regionales ha sido influyente. Para comprender cómo se ha hecho esto y cuán útil es como enfoque, primero debemos considerar las diversas formulaciones de esa ley que se han hecho. El desarrollo completo de la idea está asociado con la segunda ley de la termodinámica debido principalmente a Boltzmann (1884), aunque se basa en trabajos anteriores de Carnot (1824) y Clausius (1867). Jaynes (1957) preparó este enfoque para su aplicación en economía y Georgescu-Roegen (1971) también proporcionó una perspectiva profunda. Posteriormente, Shannon (1948) ampliaría esto al estudio de los patrones de información. Rosser Jr. (2016b) argumenta que dentro de los sistemas económicos, el primero es más apropiado cuando las fuerzas termodinámicas ontológicas están impulsando objetivamente la dinámica de un sistema. Este último es más importante como herramienta metafórica cuando surge un patrón matemático similar.

> "... la termodinámica clásica es ... la única teoría física de contenido universal de la que estoy convencido, dentro del marco del marco de aplicabilidad de sus conceptos básicos, nunca será derrocado." - Albert Einstein, citado en Rifkin (1981, pag. 44)

## Observaciones iniciales {-}

Dado que al menos los primeros esfuerzos de Alan Wilson (1967, 1970), la idea de utilizar la ley de la entropía para ayudar a modelar el desarrollo de patrones estructurales espaciales urbanos y regionales ha sido influyente. Para comprender cómo se ha hecho esto y cuán útil es como enfoque, primero debemos considerar las diversas formulaciones de esa ley que se han hecho. El desarrollo completo de la idea está asociado con la segunda ley de la termodinámica debida principalmente a Boltzmann (1884), aunque basándose en trabajos anteriores de Carnot (1824) y Clausius (1867). Jaynes1957) preparó este enfoque para su aplicación en economía con Georgescu-Roegen (1971) también proporciona una perspectiva profunda. Más tarde, Shannon (1948) lo ampliaría al estudio de los patrones de información. Rosser Jr. (2016b) sostiene que dentro de los sistemas económicos, el primero es más apropiado cuando las fuerzas termodinámicas ontológicas están impulsando objetivamente la dinámica de un sistema. Este último es más importante como herramienta metafórica cuando surge un patrón matemático similar. 1

Una forma en la que el primero puede generar patrones estructurales es a través del funcionamiento de la energía en el sistema, dado que la segunda ley de la termodinámica trata sobre cómo la energía se disipa a través de sistemas cerrados. La energía es crucial en el transporte, por lo que no debería sorprender que a medida que los costos de transporte entran en la determinación de tales patrones espaciales, podamos ver la ley de la entropía en su forma objetiva como relevante para dar forma a tales patrones y, de hecho, los costos de transporte se han considerado centrales. en la conformación de patrones espaciales urbanos y regionales que se remontan a von Thūnen (1826). Sobre la base de una propuesta de Reilly (1931) y obra de Weaver (1948). Wilson (1967, 1970, 2010) utilizaría el supuesto de minimizar los costos de transporte para modelar un sistema complejo de distribución espacial de actividades que maximizan la renta. Otro esfuerzo inicial en líneas similares se debió a Medvekov (1967).

Muchas aplicaciones de la entropía o modelos urbanos y regionales seguirían el enfoque metafórico basado en la de Shannon (1948) entropía de información. Uno de los primeros esfuerzos en este sentido se debió a Chapman (1970) para un modelo de concentración espacial o dispersión de actividades y también Batty (1976). Asimismo, esto ha apuntalado modelos de expansión urbana (Cabral et al.2013). Los índices de grados de segregación racial se han basado en tales medidas (Mora y Ruiz-Castillo,2011). Asimismo, las medidas para la diversidad del uso de la tierra se han basado en dicha entropía (Walsh y Webber,1977).

Más bien, volviendo a la formulación termodinámica fundamental, se han realizado esfuerzos para modelar la sostenibilidad ecológica de los sistemas urbanos y regionales basados ​​en sus patrones de uso de energía. La evaluación de la huella de carbono se debe a Wackernagel y Rees (1996). Aplicaciones más directas, incluido el uso del concepto de exergía, se deben a Balocco, Paeschi, Grazzini y Basosi (2000). Marchinetti, Putselli y Tierzi (2006) consideran tales modelos dentro de la dinámica de sistemas complejos de los sistemas disipativos (Prigogine1980).

Una alternativa enfatiza las fuerzas antientrópicas asociadas con la aglomeración para modelar patrones de jerarquía urbana 2 que reflejan las distribuciones de la ley de poder iniciadas por Pareto (1897), con el apoyo de Singer (1936) y Gabaix (1999). Un caso especial es la regla del tamaño de rango debido a Auerbach (1913) y Zipf (1941), con el apoyo de Batten (2001), Nitsch (2005) y Berry y Okulicz-Kozaryn (2012).

Finalmente, muchos, incluidos Papageorgiou y Smith (1983), Weidlich y Haag (1987), Krugman (1996), Portugali (1999), Gabaix y Ioannides, 2004) y Rosser Jr. (2011a). Estas interacciones pueden desencadenar las irregularidades en los caminos dinámicos que marcan los sistemas dinámicamente complejos, que seguramente son los sistemas urbanos y regionales.

La ley de la entropía, o segunda ley de la termodinámica, se convierte así en que en un sistema cerrado la entropía aumenta, lo cual fue formulado por primera vez por Clausius (1867), quien también estableció la primera ley clásica de la termodinámica de que en un sistema cerrado la cantidad de energía es constante, con esto más desarrollado por Ludwig Boltzmann (1884). La inspiración para este desarrollo provino del estudio de las máquinas de vapor por Sadi Carnot (1824). Hizo la observación crucial inicial de la primera ley, que sería crucial para comprender la imposibilidad de una máquina de movimiento perpetuo. Carnot formuló que el trabajo de una máquina de vapor provenía de la transformación de la energía térmica de una fuente más caliente a un fregadero más frío y reconoció una eficiencia máxima para esta transformación. 3 Fue de este entendimiento que Clausius derivó su conceptualización, más tarde esbozada por Boltzmann.

La variación más importante de esto sería la metafórica que mide la entropía informacional debida a Shannon (1948) y Shannon y Weaver (1949). Si bien estas dos formas de entropía se aplican a situaciones muy diferentes sin una ley ontológica de entropía que opere con respecto a la entropía informativa metafórica de Shannon, están fundamentalmente relacionadas. 4

Esta unidad fundamental se extiende a variaciones y generalizaciones posteriores del concepto de entropía desarrollado por Renyi (1961), Tsallis (1968) y Thurner y Hanel (2012). Este último se vincula con un desarrollo en Rusia de la "nueva entropía" que se vincula con la teoría de la ergodicidad donde la entropía se ve como un isomorfismo entre los estados de Bernoulli (Kolmogorov,1958; Sinaí,1959; Ornstein,1970).

## El modelo de Wilson {-}

El modelador más influyente de sistemas urbanos y regionales en utilizar el concepto de entropía ha sido Sir Alan G. Wilson (1967, 1969, 1970, 2000, 2010). Su modelo principal original era la distribución espacial de los flujos de la actividad minorista, basado en un modelo de Reilly (1931). El espacio está dividido por orígenes I y destinos j (a menudo un lugar central) de modo que S ij es una matriz de flujos de dinero desde los orígenes I a los sitios de venta minorista j . Entonces, la entropía a maximizar sujeta a las restricciones presupuestarias de los flujos viene dada por

$$\operatorname{Max} S=-\sum S_{j j} \ln S_{i j}$$

donde para los beneficios de un sitio de venta minorista dados por W j y los costos de ir desde un origen a un sitio de venta minorista dados por c ij, esto dará una distribución espacial que maximiza la renta

$$S=\Sigma W_{j} \exp \left(c_{i j}\right)$$

Esto podría modificarse aún más especificando más actividades con niveles de población y tipos de puntos de venta. En principio, esto es ampliamente consistente con el original von Thūnen (1826) modelo de alquiler con patrón de anillos alrededor de un lugar central, aunque Wilson rara vez hizo hincapié en este punto.

Este modelo básico de Wilson ha pasado desde entonces por muchas modificaciones y ampliaciones, incluidas muchas del propio Wilson, a menudo con varios coautores. Por lo tanto, si bien Wilson asumió originalmente que los costos de transporte crecen linealmente con el logaritmo de beneficios, ambos pueden ser logarítmicos, lo que podría ser cierto para un modelo de viajes largos involucrados en el transporte interurbano, con otras formas funcionales posibles a medida que las restricciones se ajustan en consecuencia (Haynes y Phillips ,1987).

El modelo también se ha ampliado a otras aplicaciones. Así, Rees y Wilson (1976) y Rogers (2008) colocó esto en modelos de flujos migratorios. Straussfogel (1991) lo utilizó en estudios de suburbanización. En los modelos de flujos comerciales, las relaciones insumo-producto pueden introducirse en modelos integrados (Kim et al.1983; Roy y Flood,1992).

Mientras que el modelo básico asumió zonas discretas, Angel y Hyman (1976) maximización de la entropía extendida a representaciones espaciales continuas. Los problemas de estimación empírica surgen en relación con la agregación y la estructura espacial en modelos de interacción espacial (Batty y Skildar,mil novecientos ochenta y dos). Se han desarrollado modelos econométricos de autocorrelación espacial en este marco (Berry et al.,2008) así como formas más amplias de interacción espacial (Fischer y Griffith, 2008).

Un mayor énfasis en un enfoque metafórico de la entropía de la información de Shannon se debió a Snickars y Weibull (1977). Fotheringham (1983) aplicó esto para el caso de zonas de destino en competencia. Smith y Hsieh (1997) introdujo un equivalente de Markov. Anas1984) vincula la maximización de la utilidad y la maximización de la entropía en estos modelos mediante un modelo logit multinomial. Wilson (2010) argumenta que estos enfoques son consistentes con la interpretación de la "complejidad desorganizada" del enfoque de la entropía de la información de Shannon según lo propuesto por Weaver (1948). Esto contrasta con el enfoque inicial de Wilson (1967, 1970) que persiguió un enfoque de entropía basándose más en Botlzmann.

Una expansión sustancial de este marco dentro del marco de Boltzmann se debió a Harris y Wilson (1978) que introdujo la dinámica lenta en el modelo. Esto tomó la forma de introducir elementos derivados de Lotka (1925) y Volterra (1938), con Wilson (2008) etiquetando el resultado de esta combinación de Boltzmann, Lotka y Volterra como el "enfoque BLV". La dinámica lenta permite el crecimiento en función de la rentabilidad de las ubicaciones dadas, siendo la dinámica rápida relacionada la dinámica de ajuste de equilibrio a más corto plazo. Esta configuración proporcionó una base para considerar modelos de bifurcaciones y cascadas catastróficas (Wilson,1981; Chalado,2009) así como dinámicas caóticas (mayo, 1973; Rosser Jr.,1991). 5

Esto eventualmente conduciría a una consideración más amplia de cómo el modelo de Wilson encaja en un marco de complejidad más amplio, especialmente vinculando con Weaver (1948) distinción entre formas de complejidad organizadas y desorganizadas. Para ello, se puede considerar que la entropía proporciona un principio organizativo clave (Wilson,2006) basándose en el enfoque BLV. Esto incluso se ha propuesto para proporcionar una explicación de cómo los modelos entrópicos de flujos de nivel inferior pueden proporcionar una base para las distribuciones de la ley de energía libre de escala de las distribuciones de los tamaños del área de asentamiento (Dearden y Wilson,2009), que consideraremos a continuación como asociado a principios organizativos antientrópicos.

## Variaciones en los modelos de distribución espacial entrópica {-}

Si bien el trabajo de Wilson inspiró un gran esfuerzo por parte de muchas personas, como se vio en la sección anterior, otros también usaron varias medidas entrópicas para estudiar distribuciones espaciales en sistemas urbanos y regionales de varias cosas. Una línea de investigación se inspiró en la aplicación de Theil (1972), que se basa en la medida de entropía de información de Shannon. Entre los primeros en hacerlo estaba Batty (1974). La versión espacial básica del índice de Theil donde H es el índice, n es el número de zonas y p i es la probabilidad de que la variable x aparezca en la zona I , está dada por

$$H_{n}=\left[\Sigma p_{i} \log \left(1 / p_{i}\right)\right] / \log n$$

Esta medida de entropía puede variar de 0 a 1, indicando este último una distribución completamente igual en las zonas espaciales, en la máxima entropía, y 0 indicando una concentración total en una zona, o un grado máximo de desigualdad y antientropía. Este índice se ha aplicado ampliamente en muchas ciencias sociales y naturales.

Batty's (1974) La variación de esta, a la que llamó entropía espacial , implica considerar lo que sucede a medida que se reduce el tamaño de las zonas, lo que también implica un número creciente de ellas. Si Δ x i es el tamaño de la zona, entonces el índice de entropía espacial Batty viene dado por

$$H=\left(\lim \Delta x_{i} \rightarrow 0\right)--\Sigma p_{i} \log \left(p_{i} / \Delta x_{i}\right)$$

Esta formulación es muy similar a la propuesta por Bailey (1990) para medir la entropía social , centrándose nuevamente en los grados de similitud o igualdad entre grupos o zonas sociales.

Entre las aplicaciones más directas de esto para los sistemas urbanos se encuentra el estudio de la expansión urbana descontrolada (Cabral et al. 2013). Una línea ha sido medir el grado de fragmentación de la propiedad. Miceli y Sirmans (2007) argumenta que esto desalienta el desarrollo, ya que los promotores inmobiliarios prefieren patrones de propiedad menos dispersos. Los patrones dispersos asociados con la expansión urbana conducen a una forma de poder monopólico que se manifiesta a través del problema de la resistencia. En términos más generales, se considera que la expansión urbana descontrolada contribuye a una variedad de problemas sociales y ambientales, con mayores costos de infraestructura e incluso mayores problemas de salud pública (Brueckner,2000; Nechyba y Walsh,2004; Frenkel y Ashkenazi,2007).

Si bien la mayoría de los observadores ven la expansión urbana descontrolada como un problema importante, tiene sus defensores. Así, Wassmer (2008) argumenta que la expansión descontrolada aumenta la satisfacción con la vivienda y las escuelas, reduce las tasas de criminalidad y aumenta la conveniencia de viajar en automóvil, aunque este último es un objetivo de quienes argumentan que la expansión descontrolada agrava los problemas ambientales. Cabral y col. (2013) ven esto como una cuestión de compensaciones. Los niveles más altos de entropía espacial exigen transporte e infraestructura, mientras que los niveles más bajos aumentan los niveles de desigualdad y fragmentación socioeconómica.

Como era de esperar, se han utilizado medidas de entropía de la información para medir los grados de segregación racial en áreas urbanas tanto para residencias como para escuelas (Mora y Ruiz-Castillo, 2011). Si bien probablemente la medida más utilizada en estos estudios es el índice de Theil que se muestra en la Ec. ( 5.3 ) anterior y propuesto por primera vez para estudiar la segregación escolar por Theil y Finizza (1971), con aplicaciones como el estudio de la segregación en el área de la Bahía de San Francisco (Miller y Quigley, 1990). Sin embargo, Mora y Ruiz-Castillo defienden la superioridad de la forma desnormalizada de este conocido como índice de información mutua, también debido a Theil (1971), que puede ser más útil para estudiar la descomponibilidad en las escuelas.

Sin embargo, otras aplicaciones espaciales incluyen la medición de la diversidad de patrones de uso de la tierra (Walsh y Webber, 1977) y distribuciones de asentamientos espaciales (Medvekov, 1967) así como los patrones espaciales de distribución de la población (Chapman, 1970). Purvis y col. (2019) proporcionan una descripción general de muchas de estas aplicaciones.

## Sistemas urbanos / regionales termodinámicamente sostenibles {-}

La mayoría de los modelos discutidos en las dos secciones anteriores se han basado en el concepto de información metafórica de entropía proveniente de Shannon y Weaver, con la posible excepción del desarrollo de Wilson de la dinámica lenta que se basa más directamente en Boltzmann. Sin embargo, otra vertiente del análisis entrópico de los sistemas urbanos y regionales se basa más en el enfoque ontológico original en el que un sistema urbano o regional se ve impulsado por la termodinámica en su sentido físico original que implica transferencias de energía y transformaciones siguiendo la Segunda Ley de la Termodinámica. Entre los que persiguen este enfoque se encuentran Rees (1992), Balocco et al. (2004), Zhang y col. (2006), Marchinetti, Pulselli y Tierzi (2006) y Purvis et al. (2019).

El enfoque de la mayor parte de esta investigación está particularmente en la sustentabilidad ecológica de los sistemas urbanos y regionales, viéndolos como sistemas disipativos abiertos que experimentan entradas y salidas de energía y materiales (Georgescu-Roegen, 1971; Prigogine,1980). Mientras que para los sistemas cerrados la entropía aumenta, con los sistemas abiertos la entropía puede aumentar o disminuir si la energía y los materiales fluyen hacia el sistema. Este fue de hecho el Schrōdinger (1945) argumento sobre la vida, que implica un proceso antientrópico mediante el cual los seres vivos extraen energía y crean orden y estructura mientras viven. Un término específico para anti-entropía es exergía (Rant,1956).

Distingamos entonces tres conceptos: entropía total o S total , entropía interior o S i , y entropía exterior o S o . Estos se relacionan dinámicamente de acuerdo con

$$\mathrm{d} S_{\text {total }} / \mathrm{d} t=\mathrm{d} S_{i} / \mathrm{d} t+\mathrm{d} S_{0} / \mathrm{d} t, \text { with } \mathrm{d} S_{i} / \mathrm{d} t>0$$

Sin embargo, d S o / d t puede ser positivo o negativo, por lo que si es negativo y tiene un valor absoluto que excede el valor absoluto que excede al de S i , entonces la entropía total puede disminuir a medida que el sistema genera orden a medida que se dibuja. en energía y materiales, solo para exportarlos como desperdicio y desorden, con la entropía aumentando fuera del sistema. Como Wackernagel y Rees (1996) lo expresaron, “Las ciudades son agujeros negros entrópicos”, lo que plantea serias dudas sobre su sostenibilidad, ya que generan grandes huellas ecológicas.

La exergía se define a menudo como la cantidad máxima de trabajo útil posible para alcanzar un estado de entropía máxima, lo que significa que debe ser cero si se logra un estado de entropía máxima. Rant's (1956) la formulación original estaba en el contexto de la ingeniería química. Si B es exergía, U es energía interna, P es presión, V es volumen, T es temperatura, S es entropía, μ i es el potencial químico del componente i, y N i son los moles del componente i , entonces la formulación de Rant es dada por

$$B=U+P V--T S-\Sigma \mu_{i} N_{i}$$

Esto implica, ceteris paribus, que

$$\mathrm{d} B / \mathrm{d} t \leq 0 \leftrightarrow \mathrm{d} S / \mathrm{d} t \geq 0$$

que destaca la interpretación de la exergía como anti-entropía. 6

Una aplicación de esto usando una modificación de la ecuación de Rant debido a Moran y Sciubba (1994) ha sido realizado por Balocco et al. (2004). Estudian la exergía involucrada en la construcción de edificios y la depreciación real en la ciudad de Castelnuovo Beardenga cerca de Siena, Italia. Esto también implica el uso de relaciones input-output involucradas con la industria de la construcción. Llegan a la conclusión de que los edificios más recientes no son tan eficientes como los más antiguos, y que los construidos en 1946-1960 proporcionan la mayor sostenibilidad.

Siguiendo a Wackernagel y Rees, así como a Balocco, Paeschi, Grazzini y Basosi, y también a Haken (1988) y Svirizhev (2000), Zhang y col. (2006) participan en un ambicioso esfuerzo para aplicar conceptos de entropía al estudio del desarrollo sostenible de Ningbo, China, una ciudad de casi 6 millones de habitantes algo al sur de Shanghai en la provincia de Zhejiang. Su esfuerzo combina tanto medidas ontológicas de entropía como de información metafórica, ya que dividen su análisis en cuatro partes. Los dos primeros están vinculados al desarrollo y mantienen la entropía de entrada y la energía de salida impuesta , que están básicamente determinadas por la producción. Los dos segundos se consideran parte del metabolismo del sistema urbano, el metabolismo regenerativo y el metabolismo destructivo . los cuales están ligados a la generación de contaminación y su saneamiento. Esto se convierte en una medida de armonía con el medio ambiente. El resultado del primero da el grado de desarrollo mientras que el segundo da el grado de armonía. Ellos estiman estos para el período 1996-2003 y encuentran que estas dos medidas generalmente iban en direcciones opuestas, con el grado de desarrollo aumentando (asociado con la disminución de la entropía) a medida que disminuía el grado de armonía (asociado con el aumento de la entropía). Esto plantea el problema de la sostenibilidad del desarrollo urbano en China de manera bastante aguda.

Marchinetti, Pulselli y Tierzi (2006) 7 considere este enfoque desde un nivel más general, basándose en ideas debidas a Morin (1995) con respecto a la autonomía versus la dependencia de los sistemas en su entorno, mientras se utiliza el enfoque de estructuras disipativas de los sistemas abiertos asociados con Prigogine (1980). Ven que los sistemas urbanos evolucionan entre los extremos de la autarquía y la globalización. Sin embargo, argumentan que al final ninguno de estos extremos es sostenible.En su defensa de un camino equilibrado, enfatizan cómo los sistemas urbanos y regionales son ecosistemas que operan sobre la base de los flujos de energía (Odum,1969) dentro de un conjunto de totalidades complejas que surgen de un conjunto de componentes de micro-nivel que interactúan (Ulanowicz, 2012).

## Procesos anti-entrópicos en sistemas urbanos / regionales {-}

Empujar contra esta versión entrópica de la estructura de los sistemas urbanos y regionales es una versión de ley de poder de dicha estructuración, al menos para ciertos casos y situaciones. Podría decirse que esto se trata en el marco de la entropía, dada la cuestión del equilibrio entre exergía y entropía en los sistemas urbanos y regionales. La mayoría de los sistemas y medidas hasta ahora han involucrado esencialmente relaciones internas o distribuciones dentro de sistemas urbanos o regionales. Pero cuando se consideran sistemas de distribución de nivel superior, la relación de entropía puede romperse o incluso volverse completamente irrelevante.

Una forma en que las fuerzas antientrópicas pueden manifestarse es mediante la aparición de distribuciones de la ley de potencia (Rosser Jr., 2016b), con evidencia sustancial de que el tamaño de las ciudades puede seguir tales distribuciones (Gabaix, 1999). Pareto (1897) identificó el concepto de distribuciones de la ley de potencias. Para P es población, r es rango y A y α son constantes, entonces

$$r P_{r}^{\alpha}=A_{i}$$

que se puede poner en forma logarítmica, que es lineal,

$$\ln r=\ln A-\alpha\left(\ln P_{r}\right)$$

Observamos que para el caso especial de α  = 1, la población de la entidad de rango r se convierte en

$$P_{r}=P_{1} / r_{i}$$

La cual fue etiquetada como la regla del tamaño de rango por Auerbach (1913) y más tarde llegaría a ser conocida como la Ley de Zipf, que se argumenta que es válida para muchas distribuciones (Zipf, 1941). 8

La cuestión de si las distribuciones del tamaño de la ciudad siguen o no la ley de Zipf y, por lo tanto, obedecen la regla del tamaño del rango, ha sido un tema de debate continuo desde Auerbach (1913) lo propuso por primera vez y Lotka (1925) lo cuestionó. Algunos, especialmente los geógrafos urbanos (Berry y Okulicz-Kozaryn,2012) han argumentado que se trata de una ley universal. Otros, más a menudo economistas, lo han cuestionado, argumentando que no hay una razón clara por la que deba seguirse, incluso si los tamaños de las ciudades pueden exhibir distribuciones de la ley de potencias (Batten,2001; Fujita y col.1999), aunque Gabaix (1999) argumenta que la Ley de Zipf surge en el límite si la Ley de Gibrat sostiene que las tasas de crecimiento son independientes del tamaño de las ciudades.

Listón2001) en particular muestra las distribuciones del tamaño de las ciudades de EE. UU. que muestran distribuciones de la ley de energía desde 1790 hasta el presente, incluso si no es exactamente la regla del tamaño de rango (con el hecho de que Los Ángeles es sustancialmente más grande que la mitad del tamaño de Nueva York, un ejemplo de por qué podría no retener). Nitsch2005) llevaron a cabo un metaestudio de estudios empíricos pasados, observando una amplia gama de hallazgos en los estudios, pero al mirarlos en conjunto encontraron una media de α  = 1.08, bastante cercana al valor de Zipf. Berry y Okulicz-Kozaryn (2012) argumentan que las variaciones en las estimaciones se deben a que no se utilizan medidas coherentes de las regiones urbanas en los estudios, y si las medidas más grandes de este tipo se utilizan en las megalópolis, entonces la ley de Zipf y la regla del tamaño del rango se cumplen plenamente. En cualquier caso, ya sea que lo haga o no, la evidencia es fuerte de que las distribuciones del tamaño de las ciudades están distribuidas por ley de poder, lo que muestra un dominio de las fuerzas antientrópicas para esta parte de los sistemas urbanos y regionales.

Una posible base para estos procesos antientrópicos que pueden generar resultados distributivos de la ley del poder son las economías de escala, conocidas desde hace mucho tiempo por ser una base también de complejidad económica (Arthur, 1994). Los sistemas urbanos en particular pueden exhibir hasta tres tipos diferentes de economías de escala: economías internas a nivel de empresa (Marshall,1879), economías de localización que implican la aglomeración externa entre empresas de una misma industria (Marshall, 1919) y economías de urbanización que involucran economías de aglomeración externa que se extienden a través de industrias (Hoover y Vernon, 1959).

Papageorgiou y Smith (1983) y Weidlich y Haag (1987). Sin embargo, desde entonces, estos modelos han sido reemplazados por los de "nueva geografía económica" que enfatizan las economías de escala que surgen dentro de la competencia monopolística, según lo analizado por Dixit y Stiglitz (1977). Mientras que Fujita (1988) comenzó a usar esto para modelar sistemas urbanos y regionales, Krugman (1991) enfoque recibió la mayor atención e influencia (Rosser Jr., 2011a).

## Complejidad, entropía y autoorganización de sistemas urbanos / regionales {-}

Esto nos lleva a darnos cuenta de que la interacción entre las fuerzas entrópicas y antientrópicas dentro de los sistemas urbanos y regionales puede generar una complejidad que subyace en el surgimiento de patrones estructurales de orden superior a través de la autoorganización, ya que los puntos de bifurcación se encuentran dentro de la dinámica no lineal de los sistemas que conducen a transformaciones estructurales morfogenéticas (Rosser Jr., 1990, 1991; Krugman,1996; Portugali,1999). Esto puede verse observando cómo operan estos sistemas desde la perspectiva de la complejidad dinámica, qué día (1994) definido como sistemas que no convergen endógenamente en un estado estacionario o crecimiento exponencial. Se sabe que tal complejidad toma cuatro formas: cibernética, teoría de catástrofes, teoría del caos y complejidad basada en agentes (Rosser Jr.,1999). Se puede ver que todas estas formas han operado dentro de los sistemas urbanos y regionales.

El modelo más importante de dinámica urbana basado en una cibernética se debió a Forrester (1961) en su Urban Dynamics , aunque etiquetó su enfoque como parte de la teoría de la dinámica de sistemas . Esto implicó un conjunto de ecuaciones en diferencias no lineales con interconexiones complicadas entre sí que implican efectos de retroalimentación positivos y negativos. Cuando se simuló, exhibió roturas estructurales y cambios repentinos en ciertos puntos, con el sistema demasiado complicado para descubrirlos mediante análisis, en lugar de requerir simulación.

Mucho más difundidos han sido los estudios de cambios estructurales en sistemas espaciales urbanos y regionales y más generales utilizando la teoría de catástrofes. Amson1974) inició el uso de la teoría de la catástrofe en tales sistemas, examinando los determinantes de la renta y la “opulencia” (atractivo) de la densidad urbana utilizando un modelo de catástrofe de cúspide. Mees1975) modeló el renacimiento de las ciudades en la Europa medieval como una catástrofe de mariposas. Wilson (1976) modeló la elección modal de transporte como una catástrofe doble, y basándose en el modelo minorista entrópico, Poston y Wilson (1977) lo hizo por el tamaño del centro comercial. 9 Isard (1977) inició el estudio de los efectos de la aglomeración provocando el surgimiento repentino de ciudades en modelos que equilibran las áreas urbanas y rurales utilizando la catástrofe de la cúspide, con Casetti (1980) y Dendrinos (1980) siguiente. Dendrinos (1978, 1979) utilizaron modelos de catástrofes de orden superior para estudiar la dinámica industrial-residencial y la formación de barrios marginales en las ciudades. Puu (1979, 1981) lo hizo también para estudiar los cambios estructurales en los patrones comerciales regionales. Nijkamp y Reggiani (1988) mostró cómo un modelo de control óptimo de interacción espacial dinámica no lineal puede generar una interpretación teórica de catástrofes.

La aplicación de la teoría del caos al estudio de dinámicas urbanas y regionales complejas fue iniciada por Beaumont, Clarke y Wilson (1981) para la dinámica residencial y comercial intraurbana, de nuevo basándose en el modelo intraurbano entrópico. Blanco (1985) combinó este modelo con ideas de sinergética (Haken, 1983) 10 para mostrar la autoorganización que surge de fluctuaciones caóticas cerca de puntos de bifurcación. Una serie de artículos y libros enfatizaron la migración interregional o la dinámica de la población más general (Rogerson,1985; Day et al.1987; Dendrinos,mil novecientos ochenta y dos; Dendrinos y Sonis,1990). Otra área de estudio fue la dinámica caótica en los modelos de ciclo económico interregional (Puu,1989, 1990). También se han realizado estudios de dinámicas caóticas en versiones extendidas de los nuevos modelos de geografía económica centro-periferia basados ​​en la competencia monopolística (Currie y Kubin,2006; Commendatore y col.2007).

Finalmente, resulta que el inicio mismo de los modelos de complejidad basados ​​en agentes surgió de los esfuerzos por modelar el surgimiento de la segregación racial en las ciudades por Schelling (1971, 1978). Estos cambios se pueden medir mediante métodos entrópicos. Curiosamente, Schelling no usó modelos analíticos ni simulación por computadora, sino que jugó un juego en un tablero Go de 19 por 19 con piedras blancas y negras, simplemente asumiendo pequeñas diferencias locales en los deseos de vivir al lado de personas como una o no. Un comienzo de integración de alta entropía termina con la aparición de un patrón segregado de baja entropía. El modelo de Schelling se ha estudiado desde entonces en muchas variaciones y contextos y se ha encontrado que es muy robusto. Zhang (2004) lo consideró como un juego evolutivo sobre un toro de celosía, mientras que Fagiolo et al. (2007) como modelo de red. Dichos modelos tienen una similitud con los modelos cibernéticos, excepto que se basan más claramente en generar una autoorganización de orden superior que surge de agentes de bajo nivel que interactúan entre sí de acuerdo con efectos estrictamente locales, un enfoque de complejidad fundamental.

## Observaciones adicionales {-}

Es completamente natural que tanto la entropía como la complejidad estén profundamente involucradas en la dinámica y las estructuras espaciales de los sistemas urbanos y regionales. La naturaleza espacial de tales sistemas los abre a que los efectos de vecindad local sean muy importantes, lo cual es fundamental para las visiones avanzadas de la complejidad y la ubicuidad de los efectos de aglomeración externos subyacen a las no linealidades que, además, conducen a complejidades dinámicas de diversos tipos, incluidas las discontinuidades catastróficas y la dinámica caótica. .

Como sistemas abiertos, la complejidad se ve reforzada por la naturaleza disipativa de los sistemas urbanos y regionales. Están sujetos a la competencia entre fuerzas entrópicas y antientrópicas que interactúan para estimular dinámicas complejas. Este es especialmente el caso de la termodinámica ontológica de los sistemas urbanos y regionales que operan como ecosistemas.

Sin embargo, las medidas de entropía metafórica basadas en la entropía de la información de Shannon han demostrado ser útiles para comprender y modelar una variedad de aspectos de los sistemas urbanos y regionales. Esto incluye tanto patrones espaciales como estructuras sociológicas como la segregación racial, que también se ha encontrado que exhiben dinámicas complejas como en el modelo de Schelling. Pocas áreas de la economía o las ciencias sociales más amplias exhiben tantos ejemplos de dinámicas complejas reforzadas por fuerzas entrópicas como los sistemas urbanos y regionales.

Esta interacción requiere una nueva visión del mundo. Como Jeremy Rifkin (1981, pag. 256) dice: “Al final, nuestro presente individual descansa para siempre en el alma colectiva del proceso de desarrollo mismo. Conservar lo mejor que podamos la dotación fija que nos quedó, y respetar lo mejor que podamos el ritmo natural que gobierna el proceso de devenir, es expresar nuestro amor último por toda la vida que nos precedió y toda la vida que vendrá después. "

## Notas al pie {-}

1. Purvis y col. (2019) abogan por un tercer tipo de entropía, "figurativa", que sugiere un creciente desorden o aleatoriedad. Sin embargo, aquí esta forma se considerará subsumida en las otras dos, especialmente en el primer Samuelson (1972) ofrece una crítica de algunos usos de la entropía en modelos económicos, así como Kovalev (2016).
2. El modelado formal de la aglomeración en sistemas urbanos se debe a Fujita (1988) y Krugman (1991) basado en Dixit y Stiglitz (1977). Véase también Fujita et al. (1999).
3. Durante mucho tiempo fue difícil encontrar una copia del libro de Carnot y durante mucho tiempo tuvo poca influencia directa en el desarrollo de las máquinas de vapor, aunque finalmente se actuó sobre su implicación de que tener una mayor diferencia de temperatura entre la fuente y el fregadero podría aumentar la eficiencia de tales máquinas. por personas como Joseph Diesel en el desarrollo de máquinas de vapor mejoradas (Georgescu-Roegen, 1971).

4 .
La distinción entre entropía ontológica y metafórica se debe a Rosser Jr. (2016b) y discutido en el capítulo anterior. Lotka (1922) argumentó que la evolución está impulsada fundamentalmente por un proceso termodinámico ontológico basado en la ley de la entropía. Brooks y col. (1989) ven la entropía de información metafórica como útil para comprender la evolución biológica.

5 .
Para sistemas alternativos que ofrecen posibilidades similares, consulte Allen y Sanglier (1979) y Nijkamp y Reggiani (1988), con Rosser Jr. (2011a) proporcionando una amplia descripción.

6 .
A veces también se conoce como negentropía , por "entropía negativa".

7 .
Irónicamente, Marchettini y los coautores están en el mismo instituto en la Universidad de Siena que Balocco y los coautores, pero ninguno de los grupos cita el trabajo del otro.

8 .
Gabaix y Ioannides (2004) argumentan que Kuznets (1955) primero proporcionó una forma formal de estimar las distribuciones de la ley de potencia para tamaños urbanos.

9 .
Wilson (1981) proporciona una descripción general temprana de muchos de estos modelos. Dendrinos y Rosser Jr. (1992) muestran cuántos están vinculados.

10 .
Las extensiones de esto a los modelos sinérgicos fractales de autoorganización de jerarquías urbanas se deben a Fotheringham et al. (1989) y Rosser Jr. (1994).