# Metamorfosis del liberalismo en el siglo XX {#MLSXX}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

La visión individualista, impulsada por la utilidad, del siglo XIX es objeto de críticas relevantes en el siglo siguiente, bajo la influencia de diferentes circunstancias: la consolidación del nacionalismo alemán; las estructuras industriales en evolución, con la consiguiente concentración del poder económico y el crecimiento de los sindicatos; la Gran Guerra y, luego, la dificultad de volver a las estructuras sociales y los arreglos económicos y monetarios de antes de la guerra; la Depresión económica y la presión por un papel más importante del Estado; y la afirmación del socialismo marxista en la Unión Soviética. Los desarrollos filosóficos —el idealismo de Croce— enfatizan los contenidos éticos de la idea liberal, que no se considera necesariamente coincidente con el liberalismo económico. Como consecuencia de estas circunstancias, el liberalismo toma diferentes direcciones: el primero enfatiza los problemas de fallas del mercado, distribución de la riqueza, presencia del Estado en la economía. El segundo tiene un acento libertario y antiestatalista, alejándose sin embargo de la Escuela Neoclásica “científica”. El tercero inserta elementos poderosos de la economía de mercado y la competencia en la tradición estatista alemana. Pigou, Keynes y Beveridge pueden considerarse economistas liberales que reaccionan a los desequilibrios de una sociedad liberal: Pigou, al insistir en las "externalidades" negativas del capitalismo, que deben ser abordadas por el Estado mediante el uso de dispositivos coercitivos para dirigir el interés propio hacia canales sociales; Keynes, al enfrentar la incapacidad del sistema para asegurar el pleno empleo y abordar la desigualdad en la distribución de la riqueza y el ingreso, y al enfatizar la economía como ciencia moral; Beveridge, ampliando el campo del liberalismo a través de una larga lista de servicios que depende del presupuesto del Estado proporcionar, incluso más allá del pleno empleo (el Estado del Bienestar). En otra dirección se mueven los economistas de la Escuela Austriaca y su principal exponente, Hayek. Su postura individualista, sin embargo, está lejos de la clásicalaissez - fairey la actitud científica y positivista de los economistas neoclásicos. Un sistema racional de preferencias, basado en la utilidad y expresado en forma matemática, no es posible, dados los fragmentos dispersos de conocimiento que están disponibles, pero el mercado proporciona la conexión necesaria entre agentes económicos “desinformados” a través del sistema de precios. Para operar, la competencia en el mercado requiere la ausencia de una planificación centralizada: solo un conjunto de reglas básicas destinadas a ser instrumentales para la búsqueda de las necesidades individuales. La Escuela de Chicago, con Friedman, reitera con énfasis esta actitud libertaria, enfocándose particularmente en la constitución monetaria, como un instrumento de estabilidad y de mantener el dinero fuera de la discreción de las autoridades. El ordoliberalismo es un giro típico del liberalismo en la Alemania de entreguerras, cuya influencia parece, sin embargo, duradera y viva en nuestros días. El Estado está en el centro mismo del sistema económico y regula y protege la competencia del mercado. El Estado debe actuar para desproletarizar las estructuras sociales del capitalismo, mejorando la libertad y responsabilidad de los trabajadores y no aprisionándolos en un estado de bienestar. El ordoliberalismo representa un fuerte giro hacia la economía normativa, en oposición a la positiva. Como tal, y de manera similar a la Escuela Histórica Alemana del siglo anterior, es inadecuado para ser estudiado como un “modelo” formal. Es más bien un esquema prescriptivo de estructura y organización del sistema económico. mejorando la libertad y la responsabilidad de los trabajadores y no aprisionándolos en un estado de bienestar. El ordoliberalismo representa un fuerte giro hacia la economía normativa, en oposición a la positiva. Como tal, y de manera similar a la Escuela Histórica Alemana del siglo anterior, es inadecuado para ser estudiado como un “modelo” formal. Es más bien un esquema prescriptivo de estructura y organización del sistema económico. mejorando la libertad y la responsabilidad de los trabajadores y no aprisionándolos en un estado de bienestar. El ordoliberalismo representa un fuerte giro hacia la economía normativa, en oposición a la positiva. Como tal, y de manera similar a la Escuela Histórica Alemana del siglo anterior, es inadecuado para ser estudiado como un “modelo” formal. Es más bien un esquema prescriptivo de estructura y organización del sistema económico.

Palabras clave

- Externalidades pigouvianas 
- Keynes 
- Estado de bienestar 
- Escuela austriaca 
- Escuela de Chicago 
- Ordoliberalismo 

## Causas del nuevo pensamiento sobre el liberalismo {-}

Si distinguimos dos temas abrumadores de cualquier doctrina económica, la producción de riqueza y su distribución, el segundo tema emerge con fuerza en el siglo XX, y el liberalismo sufre amplias y profundas metamorfosis.

El siglo pasado vio “profesiones del liberalismo cada vez más extendidas”, 1 pero declararse “liberal” podría insinuar visiones bastante diversas. La cuestión de la distribución de la riqueza, y el tema conexo de un papel más amplio del Estado en la economía, significó, por un lado, avanzar hacia ideas más cercanas al estatismo y al socialismo, como en el caso del socialismo liberal, la economía social de mercado, incluso el ordoliberalismo 2 . ideas a veces vistas como una “tercera vía”, como una alternativa entre el liberalismo y el socialismo. Por otro lado, significó un alejamiento del “cosmopolitismo” de los pensadores clásicos —que había sido un hito del liberalismo decimonónico— hacia una nueva relevancia del interés nacional.

Estas tendencias, sin embargo, no agotaron el amplio campo de las profesiones del liberalismo, porque, al mismo tiempo, un fuerte componente ideológico también estuvo presente en las teorías libertarias que afirmaron el valor ético de reinstaurar la posición central del individuo como agente económico.

Las relaciones entre diferentes corrientes de pensamiento se volvieron borrosas. A menudo dificultaban descubrir la filosofía subyacente de una teoría económica y evaluar hasta qué punto las visiones liberalistas, socialistas y nacionalistas podían converger en la misma persona; Además, la filosofía económica de un escritor podría cambiar y su teoría económica podría verse afectada como resultado. 3

¿Cómo podemos resumir la actitud de una mente liberal a principios del siglo XX, tal como la moldearon las doctrinas económicas clásicas y luego neoclásicas del siglo XIX? ¿Hubo una sabiduría común, o al menos una opinión predominante, del hombre liberal en el cambio de siglo, tal como se plasmó en las convenciones sociales, o incluso religiosas, y en las teorías económicas centradas en el concepto de la utilidad individual del hombre? Keynes ofrece un buen currículum vitaede este consenso, al observar, en 1926: “Trazo la unidad peculiar de la filosofía política cotidiana del siglo XIX hasta el éxito con el que armonizó escuelas diversificadas y en guerra y unió todas las cosas buenas en una sola mano. Hume y Paley, Burke y Rousseau, Goodwin y Malthus, Cobbet y Huskisson, Bentham y Coleridge, Darwin y el obispo de Oxford, fueron todos, se descubrió, alcanzando prácticamente lo mismo: el individualismo y el laissez-faire ... la compañía del los economistas estaban allí para demostrar que la menor desviación hacia la impiedad [es decir, un desapego de esa sabiduría consolidada] implicaba la ruina financiera. Estas razones y esta atmósfera son las explicaciones ... por qué sentimos un sesgo tan fuerte a favor del laissez-faire y por qué la acción del Estado para regular el valor del dinero, o el curso de la inversión,4

¿Podemos ver esa sabiduría común, tal como la expone Keynes, como una visión realmente liberal? ¿O debería el liberalismo tener un espacio conceptual más amplio (ético, político) y no necesariamente identificarse con el liberalismo económico impulsado por la utilidad que surgió de ese enfoque? Como veremos, Keynes afirmaría explícitamente que la economía es una ciencia moral. 5 Encontró “repugnante” la “mezcla de lenguaje hegeliano y biológico”, 6 rechazando así tanto cualquier visión estatista como la actitud positivista de los economistas neoclásicos. La pregunta surgió del descontento de varios pensadores, y varios factores contribuyeron a reexaminar la relación entre el liberalismo y esa visión individualista, como sigue.

### Factores políticos, económicos y sociales {-}

Hasta que Gran Bretaña mantuvo su posición hegemónica, prevaleció una visión global o “cosmopolita”, parte esencial del análisis clásico y neoclásico. Durante mucho tiempo, el crecimiento del nacionalismo, con el establecimiento y consolidación de estados a menudo poderosos, y el atractivo internacional del socialismo, no fueron suficientes para desafiar esa posición intelectual y política preeminente. La libertad de empresa y la libertad de intercambio en mercados competitivos, y un conjunto de instituciones funcionales a ese sistema económico, fueron el corolario de esta visión.

Pero estaba surgiendo un peso cada vez mayor de Alemania, desafiando la supremacía británica. Alemania se posicionó, al mismo tiempo, como el principal antagonista político de Gran Bretaña y la expresión de filosofías económicas, y políticas económicas, bastante lejos de esa perspectiva liberal imperante en Gran Bretaña. En las últimas décadas del siglo XIX, los intelectuales británicos advirtieron a su propio país que la educación nacional y la disciplina nacional "en el corazón teutónico de Europa" estaban creando un nuevo poder que desafiaba celosamente la "riqueza mal distribuida" de Gran Bretaña. 7Como se mencionó en el capítulo anterior, según las estimaciones de hoy, en los primeros años del nuevo siglo el PIB per cápita alemán superó al británico. Este tipo de estadísticas no estaba disponible para los contemporáneos, pero pudieron ver el éxito de los enfoques intelectuales y políticos alemanes, su peso creciente en la economía internacional y la confianza de Alemania en una visión centrada en el Estado sobre la perspectiva cosmopolita y enfocada individualmente. La Entente Cordiale entre Gran Bretaña y Francia (1904) puede verse desde esta perspectiva.

Al mismo tiempo, una estructura productiva cambiante de los países industriales, bastante alejada de la existente en la Gran Bretaña de Adam Smith, dificultaba la puesta en práctica de un mercado realmente libre, la condición previa asumida por la economía neoclásica para una competencia sin trabas. . De hecho, esta estructura en evolución estaba formada por grandes complejos industriales y planteaba nuevos problemas que afectaban la concentración del poder económico y la alteración del sistema de precios. De ahí la necesidad de poner barreras a los cárteles y monopolios industriales. La competencia no se puede dar por sentada. Como hemos visto anteriormente (Capítulo 1 Marshall en particular), el tema de la competencia surge en la literatura de los economistas neoclásicos, pero aún con una actitud cautelosa, en la incertidumbre de que la libertad del empresario pueda verse afectada negativamente.

“El sistema en el que [el pueblo estadounidense] tenía confianza —escribe Herbert Stein con referencia al capitalismo de su país en la década de 1920— no era el sistema de libre mercado de competencia atomista, de la Mano Invisible. Era el sistema empresarial, que es otra cosa. Era un sistema, en el que los beneficios fluían del carácter y la sabiduría de empresarios identificables ”. 8

En estos nuevos modos de producción los trabajadores tomarían cada vez más conciencia de sus condiciones, no solo en lo que respecta a su remuneración, sino también a sus necesidades de salud y jubilación, y tratarían de alcanzar la igualdad social. Bajo el mismo techo de enormes fábricas, los trabajadores vivían muy cerca y así podían organizarse en sindicatos. Los sindicatos de trabajadores aumentaron sus voces contra “la capital”. Se reclamaría una distribución más equitativa del producto industrial. La visión socialista iba ganando terreno, tanto en la versión marxista como en otras corrientes de pensamiento no tan extremas. Este fue, por ejemplo, el caso de Gran Bretaña, donde poco antes de la Primera Guerra Mundial, grupos de socialistas numéricamente significativos se reunieron bajo la bandera de la sociedad fabiana. 9

### La guerra {-}

La Gran Guerra da otro golpe fuerte a la visión económica liberal: vemos intervenciones del Estado en la vida económica para financiar el esfuerzo bélico y organizar a toda la sociedad junto con esquemas funcionales a los propósitos bélicos; se introducen obstáculos al comercio internacional; en todas partes, se registra una expansión anormal de la oferta monetaria y la inflación y, como consecuencia, el patrón oro, el sistema monetario como emblema de la sociedad liberal, se suspende en todos los países involucrados en la guerra, con la excepción de Estados Unidos. . Pero, no por casualidad, “suspensión” fue la palabra, porque todos los gobiernos tenían en mente, una vez cerrado el paréntesis de la guerra, restaurar las condiciones económicas y monetarias que antes imperaban, la libertad de cambio, la globalización perdida.

Sin embargo, son vanos los intentos de los ganadores y los perdedores de volver a las condiciones económicas y sociales de antes de la guerra. No nos detendremos en la evolución política de estos años de posguerra. Basta recordar algunos desarrollos relevantes. No solo el Imperio Ruso había desaparecido totalmente del concierto de las grandes potencias, sino que el Estado soviético se proponía como una alternativa radical al Estado liberal y como un sistema de gobierno que buscaba una plena puesta en práctica de esa filosofía socialista que hemos descrito. en el capítulo anterior, poniendo patas arriba los arreglos sociales preexistentes, erigiéndose como una antítesis del orden capitalista liberal y finalmente estableciendo un orden proletario sobre una base mundana.

En otros lugares, se estaban produciendo cambios importantes: la difícil reconversión industrial de la guerra a la paz, la inflación duradera, el malestar social, en parte relacionado con el descontento y la ilusión de los veteranos, y también alimentado por la propaganda socialista y por la observación de lo que estaba sucediendo en Rusia. , las reparaciones de guerra golpean a la derrotada Alemania, el peso de la deuda entre los Aliados sobre las finanzas públicas. Todos estos factores dificultaron enormemente cualquier esfuerzo por volver a las estructuras sociales y los acuerdos económicos y monetarios de antes de la guerra. De hecho, hubo un retorno a las instituciones de antes de la guerra, incluida una reconstrucción del patrón oro, pero esto sucedió sobre la base de tipos de cambio que no reflejaban las condiciones económicas y financieras de los respectivos países, y sin embargo en un contexto de difíciles condiciones sociales que dificultaron cualquier "juego según las reglas", en primer lugar, la deflación de precios y salarios necesaria para que los países sean competitivos internacionalmente. Durante la década de 1920, el globalismo de antes de la guerra se apoyó en cimientos frágiles.

Los movimientos internacionales de mercancías y capitales, alentados por la precaria restauración de tipos de cambio fijos, favorecieron a las economías que habían salido de la guerra en mejor forma (Estados Unidos), o habían sido lo suficientemente astutas para volver al patrón oro con un intercambio competitivo. tarifas (Francia). A las economías más desfavorecidas por el retorno de sus monedas a la paridad del oro a tasas poco realistas, a veces alentadas por razones de prestigio político (ver la “cuota 90” de Mussolini 10), apegarse a esa paridad significaba un ejercicio inútil y costoso, no solo en términos de producción, sino también en términos de deflación interna y malestar social. Lo que pasó bajo el nombre de “guerra de dinero” representó una perturbación mucho más profunda, fue evidencia de la desintegración del orden internacional, atestiguada por el fracaso sustancial de la Sociedad de Naciones. El antiglobalismo, en formas fuertemente nacionalistas y corporativas, y el socialismo, tomaron la delantera.

Todos estos factores crearon un entorno propicio para el éxito de diferentes teorías económicas, apoyadas ambas en la figura abrumadora del Estado: el Estado ético en la raíz del nacionalismo, y el materialismo histórico del socialismo marxista conducente al Estado proletario.

### La gran Depresión {-}

El colapso financiero y la consiguiente Gran Depresión fueron una razón más para repensar esquemas anteriores de pensamiento económico. Los economistas neoclásicos, centrados en las teorías walrasianas del equilibrio general, no tenían la clave para poner estos eventos en sus esquemas lógicos, y sus explicaciones, principalmente monetarias, de la crisis sufrieron irrelevancia. El economista estadounidense Irving Fisher escribió en The New York Times, poco antes del colapso, que el mercado de valores había alcanzado lo que parecía una "meseta permanentemente alta"; y después del accidente, agregó que el deslizamiento fue solo temporal. El desconcierto intelectual y político que acompañó al colapso, el colapso de la producción y el sufrimiento social en varias de las principales economías, se han descrito extensamente en otros lugares y aquí no hay necesidad de dedicar más palabras a eso.

La sensación de crisis que había traído el nuevo siglo, la agitación económica y social relacionada con la Primera Guerra Mundial, ya había hecho que el siglo anterior pareciera una larga fase de tranquilidad, estabilidad económica y social, para entonces definitivamente perdida. En este entorno, la Gran Depresión se notó aún más con una sensación de sorpresa no deseada porque, de hecho, había seguido a casi una década de crecimiento económico y euforia financiera. Fortaleció la búsqueda de nuevas formas de abordar estos nuevos desafíos. El pensamiento liberal necesitaba una reevaluación.

La Depresión reforzó el atractivo de las ideologías muy lejos de la idea liberal. Por un lado, los países nacionalistas encontraron en estos desarrollos una confirmación de la necesidad de un papel importante del Estado en la economía, facilitado políticamente por el mismo autoritarismo de sus gobernantes. Por otro lado, la Unión Soviética y los economistas marxistas de todo el mundo podían contemplar con complacencia un crecimiento aparentemente ininterrumpido de su economía hasta la Segunda Guerra Mundial, ciegos ante los horrores de su régimen (véase el capítulo 3 ). 

Basil Blackett, director del Banco de Inglaterra y, con título completo, miembro del establecimiento británico, expresa bien la conciencia de estas nuevas condiciones, quien observó, en 1931: “La difusión de la técnica de la organización sindical y paralelamente al aumento de la conciencia humanitaria y social sobre los problemas de vivienda, salud, saneamiento y condiciones de trabajo en general, han hecho imposibles o inadmisibles muchos de esos brutales ajustes económicos que nuestros abuelos pudieron considerar como consecuencia de la intervención. de una providencia sabia, que utilizó el interés propio ilustrado y la competitividad humana no regulada como su medio misterioso para realizar maravillas en la causa del progreso moral y material ”. 11

### Desarrollos filosóficos: historicismo ideal {-}

En las primeras décadas del siglo surgieron diferentes visiones del liberalismo, hasta entonces centradas en los factores económicos: después de la Ilustración, el historicismo, el marxismo y el positivismo, nuevas líneas del pensamiento liberal miraron la relación entre Economía y Moralidad, como el “historicismo ideal”. ”Del filósofo italiano Benedetto Croce y sus seguidores, como Robin G. Collingwood en Gran Bretaña.

En cuanto a Economía y moralidad, el problema de la relación entre la Filosofía de la economía y la Ciencia de la economía fue planteado en términos radicales, desplazando a Croce en varias obras, siendo la principal publicada en 1908. 12 Su enfoque de este tema debe ser puesto en el marco de su propio sistema filosófico, que clasifica tanto la economía como la moral dentro de un mismo campo de la “Filosofía de lo práctico”. 13

Para explicar su sistema y cómo está conectado a la economía, Croce se remonta al origen de la economía política en términos bastante similares a los de Schumpeter (ver arriba, Capítulo 1 ): es en el siglo XVIII cuando los filósofos escoceses, como Hutcheson y Hume, querían "poner la boca" ( mettere bocca ) sobre economía y, a su vez, los economistas no querían descuidar las cuestiones relacionadas con la ética. Adam Smith, a la vez filósofo y economista, es la expresión de esta tendencia. Sin embargo, con el tiempo, los economistas introdujeron el concepto de utilidad como una cuestión de “especulación” individual, desprovista de contenido ético. El núcleo del desacuerdo, que hemos mencionado anteriormente, estaba en el concepto de “valor”: un concepto objetivo, inspirado en instancias morales, con el primero; y una subjetiva, inspirada en consideraciones puramente económicas, hasta el extremo hedonistas, siendo esta última: una diferencia entre “valor como es y valor como, en cierto modo, debe ser”. 14

Con una notable similitud de acentos entre él y los marxistas del siglo XX (cuyas ideas sobre economía política se abordarán en el capítulo 3 ), Croce: (a) ataca la banalización del concepto de utilidad de los economistas neoclásicos, (b) reduce la ciencia económica a sus esquemas abstractos, y (c) cree que esta ciencia económica específica —abstracta e individualmente utilitaria— no tiene nada que ver con ninguna idea filosófica de utilidad. 

Para ser claro en este punto, debe enfatizarse que Croce identifica la economía con las teorías neoclásicas y descuida totalmente otras direcciones alternativas que fueron tomadas por la disciplina económica, la economía keynesiana, por ejemplo. De hecho, no he encontrado ninguna evidencia de la reacción de Croce al pensamiento keynesiano, en particular a la firme visión de Keynes de que la economía es “una ciencia moral”. Es una cuestión de especulación que la reacción de Croce hubiera sido muy comprensiva. 15 Esto explica por qué muchos economistas, incluso respetuosos de Croce como filósofo e historiador, se han quejado con pesar de que Croce no entendía economía.

Sólo confinando la economía en los límites de una ciencia utilitaria individual es posible aceptar la idea de Croce de que las acciones económicas y morales deben mantenerse distintas: la primera tiene que ver con la búsqueda egoísta de la utilidad, como lo explican los economistas neoclásicos; y el segundo, con la búsqueda de un nivel superior de “pensamiento universal” (“utilidad”, en términos filosóficos).

Lo que significa este “pensamiento universal”, el propio Croce subraya que no tiene un contenido específico 16 ; con certeza, no se resuelve simplemente en el altruismo, la observancia religiosa u otros conceptos similares, ni se limita a un genérico “hacer el bien”, en el sentido común de la palabra. Significa, más bien, ir más allá del propósito egoísta y comportarse de conformidad con el interés general de toda la humanidad, como emergiendo de las circunstancias históricas reales del tiempo y lugar bajo las cuales el individuo tiene que actuar (este es el “ historicismo ideal ”de la filosofía de Croce).

Por muy abstracta que pueda ser esta idea, se comprende mejor si se traduce a terminología concreta —práctica, si queremos—. El enfoque de Croce, en ese momento histórico específico (es decir, en el momento de su escritura, principios del siglo XX), puede verse como "pedagogía política, un intento de educar a la clase dominante italiana para que esté a la altura de sus deberes". , una invitación a mirar un contexto europeo más amplio y abandonar los sueños nacionalistas y coloniales entonces generalizados. Al mismo tiempo, Croce, un antimarxista intransigente, busca mantener un equilibrio entre los intereses contrastantes de las diferentes clases sociales, sin dar lugar a los impulsos social revolucionarios. 17

Este es el núcleo del liberalismo en el pensamiento de Croce: los esquemas intelectuales históricamente determinados —también en el campo de la economía— no deben confundirse con ideas de validez universal y atemporal. Aquí cesa toda simpatía por los economistas británicos de la Ilustración, de la escuela clásica. No puede aceptar el esquema ricardiano de ideas que tienen validez “en todos los lugares y en todos los tiempos” (ver arriba, Capítulo 1 ). 18 

Por eso Croce trae un ataque a todas las teorías económicas desarrolladas en el transcurso del siglo anterior:

Sobre la escuela clásica: “los conceptos empíricos del liberismo (liberismo, como liberalismo económico 19 ) fueron elevados al nivel de leyes naturales. Sin embargo, no tenían un valor absoluto, sino simplemente empíricos, es decir, basados ​​en hechos históricos y contingentes. Los economistas que formularon y apoyaron esas 'leyes' defendieron, en nombre de la ciencia, intereses particulares de ciertas clases sociales 20 (esto se parece a Marx) ”.

Respecto a la Escuela Histórica Alemana: “se soñó, especialmente por los economistas alemanes,… con una ciencia económica fundada en la ética”, pero la Escuela confunde valores económicos y éticos, y en la práctica favorece los intereses de ciertas naciones. 21

Y sobre los economistas neoclásicos: “la aplicación de las matemáticas a la ciencia económica se ha hecho similar a la aplicación de las matemáticas a la mecánica; y el homo oeconomicus ha aparecido totalmente similar al 'punto material' en la mecánica ”... El límite de este enfoque está en el hecho de que la economía basada en el concepto de utilidad descuida las distinciones cualitativas, y no puede dar ninguna relevancia a los hechos morales [que se entiende en el sentido croceano como se explicó anteriormente]. Los dos órdenes de actos son, en el esquema neoclásico de la "economía pura", indistinguibles. La economía pura, que trabaja a través del lenguaje matemático, tiene una base sólida, si dejamos de lado el hecho de que no considera ni el más mínimo vestigio del concepto de acción humana. 22Croce añade: “[En conjunto] la naturaleza de la disciplina económica como disciplina cuantitativa… donde no se puede superar el atomismo de postulados y definiciones, no permite su desarrollo orgánico a partir de un principio superior, que sólo pertenece a la filosofía”. 23

Entre la filosofía de la economía y la ciencia económica no puede haber desacuerdo, porque son conceptos heterogéneos. La filosofía cometería un abuso si invadiera el campo de la economía. Mezclar los dos — piensa Croce — da origen a al menos tres errores: (1) ver el cálculo económico como el único capaz de dar al hombre todas las verdades que necesita: “a los economistas más puros y matemáticos - escribe Croce irónicamente - Me gustaría decir: libérate de las penas de filosofar: calcula, no pienses ”; (2) el nacionalismo y el liberalismo económico son hechos históricos, no “leyes”, y los economistas que sostienen la primera o la segunda no son científicos, sino políticos; (3) homo oeconomicus, constructor de diagramas y calculador de niveles de utilidad y curvas de indiferencia, se cree que es un animal realmente existente, pero el balance de la vida humana no se puede construir como una cuenta de pérdidas / ganancias, medido según su intensidad o duración. Esto genera “la creencia falaz de que las construcciones matemáticas y el cálculo económico se identifican con la psique real [del hombre] o el Espíritu”. 24

Croce, al identificar la economía con el pensamiento neoclásico entonces imperante, se ve conducido a una actitud escéptica hacia la disciplina económica en general: observa la debilidad filosófica de los principios adoptados por estos economistas como fundamento de sus teorías, y muestra una actitud de superioridad, cordialmente correspondida por los economistas con los que mantuvo largos y duros debates, en particular con Pareto 25 y Einaudi, a pesar de la actitud deferente y generosa de Einaudi hacia el filósofo (véase también el capítulo 5 ). 

Si el acto económico se descarta simplemente como resultado del egoísmo individual, y la disciplina económica se abstiene de considerar sus implicaciones sociales más amplias y profundas, se niega la presencia de cualquier “visión” en el establecimiento de los términos del análisis económico. Esto puede explicar el papel relativamente menor que desempeñaron los acontecimientos económicos en las principales obras históricas de Croce.

Esta larga digresión sobre la relación difícil, casi dolorosa entre Croce y la disciplina económica debería ayudar a definir un enfoque de nuestro tema de las “filosofías económicas” a lo largo de algunos conceptos:

1. Cualquier teoría económica que aspire a escalar por encima del nivel de la “economía vulgar” debe basarse en postulados que en su mayoría son de carácter no económico.
2. no hay una visión única, exclusiva y correcta que sustente la teoría económica, y como consecuencia no puede haber una única teoría económica superior. Sólo una visión que responda al avance del espíritu humano en un tiempo y lugar determinados tiene derecho a ser definida como "liberal";
3. como consecuencia, el liberalismo puede comprender diversas organizaciones sociales y económicas, cuerpos de instituciones, modos de producción, que no son necesariamente válidos “en todo momento y lugar” (para usar, nuevamente, la terminología de Ricardo, ver Capítulo 1 ), pero relacionados con las circunstancias históricas específicas en las que surgen y se desarrollan (listas, por así decirlo, para ser reemplazadas por otras cuando llegue el momento). 
4. la conexión entre el liberalismo ético y el liberalismo económico tiene, por tanto, sólo un carácter histórico. La dificultad surge cuando el liberalismo económico reivindica para sí el valor de la ley suprema de la vida social e insiste en estar cerca del liberalismo ético, que, a su vez, se considera a sí mismo como la ley suprema de la vida social. “Dos leyes de igual rango y sobre un mismo asunto son demasiadas, una es redundante”. Dado que el liberalismo ético rechaza cualquier regulación autoritaria de la actividad económica como una mortificación de la inventiva humana, avanza en la misma línea del liberalismo económico. Es posible —escribe Croce— que el liberalismo apruebe muchos de los preceptos del liberalismo económico, que han traído tantos beneficios a la civilización moderna; pero esta aprobación se da por motivos éticos, no económicos.26 sino más bien si es “liberal”; no si es cuantitativamente productivo, sino cualitativamente valioso. 27

El verdadero hombre liberal, si seguimos el razonamiento de Croce, tiene en mente un valor ético superior - “universal” - que, según diversas circunstancias históricas, puede subsumir cualquier teoría económica que sea la más adecuada para afrontar la situación contingente que tiene. para afrontar y resolver. 28

El enfoque intelectual de Croce está lejos del del economista, pero las cuestiones filosóficas que plantea responden a necesidades que también son relevantes para la disciplina económica. 29

La afirmación de los Estados totalitarios en las décadas posteriores a la Primera Guerra Mundial, llevó a Croce a nuevas reflexiones sobre el liberalismo, su fundamento ético y su relación con la disciplina económica. Dio pruebas de lo que debe ser un medio liberal en las circunstancias políticas y económicas específicas de esos años. En 1925, Croce observó: “Es con particular insistencia que escuchamos en estos días que la idea del liberalismo ya se ha extinguido, y que el mundo de hoy y de mañana pertenece a la oposición y lucha entre dos tendencias fundamentales, el socialismo y el comunismo en uno. de lado, y reacción o fascismo del otro ”. 30Croce no entró en el dominio de la economía, pero reconoció que la superioridad de la idea liberal radicaba precisamente en la "necesidad de mantener, en la medida de lo posible, un campo de juego libre para las fuerzas espontáneas e inventivas de los individuos y los grupos sociales, porque sólo de estas fuerzas se puede esperar cualquier progreso mental, moral y económico ”. Y agregó, para confirmar al liberalismo como una idea ética que está por encima de cualquier arreglo político, económico o institucional: “A un liberal verdaderamente consciente le suena imposible adherirse a ideales autoritarios y reaccionarios, o comunistas, porque el liberalismo los incluye a todos, dentro de sus límites aceptables ”. 31

Vale la pena recalcar nuevamente que, según él, el liberalismo, como idea ética, debe identificarse con la evolución dialéctica de la historia humana misma: dialéctica, porque es capaz de incluir las diversas organizaciones de la economía, la política, el derecho. El liberalismo bien puede aceptar organizaciones de propiedad y producción diferentes y cambiantes. El liberalismo tout court y el liberalismo económico, o "liberismo", bien pueden coexistir, pero su conexión es de carácter histórico relativo. El liberalismo económico no puede verse como una regla de vida suprema; por el contrario, se puede hablar de un “socialismo liberal”, cuando las medidas que la doctrina económica califica como “socialistas” son coherentes con la visión liberal, definida como antes.32 [“di che lacrime grondi e di che sangue”]. 33

Secciones  2 - 5 de este capítulo tratan formas de liberalismo que hacen hincapié en el contenido ético de la idea, y adoptar una postura crítica frente a dejar hacer. Las secciones  6 y 7 se centran en el aspecto explícitamente libertario del liberalismo; Sin embargo, alejándose de la doctrina positivista relacionada con las ciencias naturales de los economistas neoclásicos, estos pensadores subrayan el valor moral del individualismo económico. La sección  8 está dedicada a esa peculiar forma de liberalismo que es el ordoliberalismo —en su mayoría alemán—.

## El estatismo de Rathenau frente al "liberismo" de Einaudi {-}

Con la guerra aún en curso, un singular industrial, estadista e intelectual de Alemania, Walther Rathenau, observó que “de la catástrofe económica mundial más grande de la historia no podemos deshacernos de los arreglos financieros manchados y los viejos dispositivos de expiación como préstamos, derechos y monopolios ”. 34Por tanto, no debemos dar un paso atrás en “interferir en la libertad industrial y los derechos personales, en la colaboración del Estado y la igualdad social, incluso en los trastornos sociales y geográficos”. Rathenau criticó el sistema económico liberal y se basó en la experiencia de la economía de guerra planificada, es decir, en "el sistema de disciplina económica del Estado". Señaló críticamente que los liberales querían abolir esa "disciplina económica" una vez que terminara la guerra para que "la libertad económica y la superlibertad pudieran ser restauradas, a veces confiando en las necesidades de la empresa privada para encontrar direcciones para nuestra vida colectiva". 35En cambio, buscaba la especialización y la coordinación productiva, lo que podría eliminar las duplicaciones y el desperdicio en la producción de la misma mercancía, eliminar gradualmente la competencia desenfrenada, presagio de gastos inútiles "para atraer clientes". 36 “No es cierto - escribió Rathenau - que una ansiedad desesperada por ser competitivos nos hace más fuertes ... [S] e que, en el año siguiente, los derrotados intentarán ansiosamente vencer al ganador, sería mejor para ellos alcanzar un acuerdo, en lugar de pelearnos sobre nuestros hombros la lucha por la supremacía en ser capaces e inventivos ”. 37También creía en el proteccionismo en el comercio de productos básicos y en las cuotas de importación. Su programa debería haber sido promulgado a través de sindicatos de profesiones y sindicatos industriales, que deben ser corporaciones reconocidas y supervisadas por el Estado con amplios poderes de intervención. 38 “¡Alguien dirá - agregó Rathenau - que estos son los viejos gremios y las viejas corporaciones de artes y oficios!” En absoluto, respondió. Los sindicatos son un "colectivo" de producción, "donde todos los miembros están unidos orgánicamente ... unidos en una unidad viva ... no una confederación sino un organismo". 39 Y, sin embargo, “La nueva economía no será una economía de Estado, sino una economía privada sujeta al juicio de los poderes públicos, una economía privada… que necesitará la colaboración del Estado”. 40Lo que tenemos aquí con Rathenau es una visión pro-estatal, proteccionista y corporativista, que es la antítesis del pensamiento liberal. Como se observará fácilmente, su filosofía es similar a la de List (véase el capítulo 1 ) y al naciente corporativismo italiano (véase el capítulo 3 ).  

Por tanto, no es casualidad que se pueda encontrar una feroz crítica al libro de Rathenau en la reseña escrita poco después de su publicación por el economista liberal Luigi Einaudi. Refiriéndose al libro de Rathenau, rechazó la idea de que la guerra en curso era "la hoguera del viejo mundo económico", y observó que el pensamiento de Rathenau era "poco claro, vago, indefinido". “La guerra actual - escribe Einaudi - no es diferente de tantas otras guerras, salvo la adopción de nuevas técnicas, ... y sus consecuencias serán similares ... La cultura de Rathenau no es realmente profunda, necesita creer en una palabra regeneración ... y él piensa ser el profeta de este nuevo orden económico ”. El liberalismo de Einaudi no puede aceptar la creación, bajo la dirección del Estado, de sindicatos profesionales e industriales, o cárteles. “La voluntad de operar de acuerdo con el propio deber, de actuar con sabiduría,41

Los principales puntos de la visión económica de Einaudi se pueden resumir de la siguiente manera:

> un sistema económico basado en la libre lucha de los agentes económicos;
>
> el componente moral de esta lucha;
>
> el rol del Estado en permitir que esta lucha se desarrolle con equidad, sin injerencias pero asegurando la igualdad de oportunidades para todos los actores;
>
> una hacienda pública diseñada para hacer del Estado un factor de producción.

Como veremos, el liberalismo de Einaudi se acerca bastante al de Hayek, en su insistencia en el valor ético de la libertad individual, y al de los ordoliberales, al enfatizar el fuerte papel del Estado.

Podemos considerar por separado los puntos de su filosofía económica.

Respecto al primer punto, Einaudi puede ser visto como perteneciente a la corriente de economistas adheridos a la revolución marginalista neoclásica y, en realidad, no aporta aportes teóricos relevantes a ese esquema lógico, pero su interés no está tanto en el nivel de equilibrio alcanzado por una economía que opera en un régimen de libre competencia, como en la forma en que se alcanza el equilibrio económico. 42 Observa que el equilibrio general walrasiano del sistema económico no puede ser el resultado del funcionamiento espontáneo de los agentes económicos, cuya interacción tiene una explicación mecánica, matemáticamente expresada, sino que se alcanza a través de una lucha interminable de esos agentes económicos, individuos y empresas.

El segundo punto significa que esta lucha tiene un sentido moral, es vista como expresión de libertad. Para dar ejemplos, con referencia a las fuerzas en conflicto de trabajadores y empresarios, Einaudi escribe: “Un industrial es liberal si cree en su propio espíritu de iniciativa… es socialista cuando pide deberes protectores por parte del Estado. Un trabajador es liberal si se une a sus compañeros de trabajo para crear un instrumento común de cooperación o defensa; es socialista si invoca al Estado un privilegio exclusivo para proteger su organización, o pide una ley o sentencia judicial que prohíba las obras a los rompehuelgas ... Liberal es aquel que cree en la mejora material o moral lograda a través del esfuerzo voluntario, el sacrificio y voluntad de trabajar en armonía con los demás; socialista es el que quiere imponer la mejora a través de la fuerza ”.43 Por lo tanto, favorece los sindicatos de libre creación como instrumento de esa lucha, pero rechaza enérgicamente los subsidios o la protección que otorga el Estado a uno u otro lado de la lucha. Este aspecto ético de la libre competencia acerca el pensamiento de Einaudi a la Escuela Clásica de Adam Smith; suWeltanshauungno puedecompararsecon el enfoque "científico" que mantiene la ética fuera de la economía.

Tercer punto: Einaudi es consciente del papel central, aunque cuantitativamente limitado, del Estado en la economía. Para ello, el propio Estado debe estar en sintonía con el sistema económico libre: no puede ser una entidad autoritaria. Tenemos aquí una inversión del esquema de Croce: según Croce, un Estado liberal puede ser compatible con sistemas económicos que no necesariamente deben identificarse con el liberalismo económico. Según Einaudi, la idea liberal es seguramente ética, pero una sola idea, porque no se puede hacer una distinción entre liberalismo ético y económico, son exactamente el mismo concepto: este es el principal punto de contraste con Croce.

El papel del Estado no es solo de no injerencia en la lucha, sino también de preservar y mejorar la competencia justa. En cuanto al mercado, la intervención del Estado consistirá en primer lugar en combatir los monopolios privados y transformar los monopolios naturales en servicios públicos. En cuanto a los agentes económicos, el Estado tiene un rol proactivo, que es otro aspecto de la visión del liberalismo como lucha: como liberal, Einaudi no puede aceptar el concepto de igualdad absoluta de los agentes (está claro que está más cerca de La visión moderada de Adam Smith, que a la visión igualitaria de la Ilustración radical francesa); pero piensa que la prioridad de un Estado es asegurar la igualdad desde el principio, es decir, en términos de oportunidades que cualquier persona debe tener. Solo este tipo de igualdad puede permitir que una lucha se libere en términos justos. Significa "bajar los picos" mediante la tributación progresiva y "subir los mínimos" mediante la legislación social, en lo que respecta al salario mínimo, la limitación de los horarios de trabajo, la prohibición del trabajo infantil, la protección extendida a los trabajadores no sindicalizados, el seguro contra accidentes de trabajo, la discapacidad y pensiones de jubilación. Esta legislación social, lejos de estar en contradicción con el Estado liberal, es la condición previa para estar más cerca de esa hipótesis abstracta de la libre competencia que es el eje principal del pensamiento económico liberal.44

El enfoque de Einaudi parece aquí cercano al pensamiento ordoliberal, madurando exactamente en ese período en Alemania. Los ordoliberales pensaban que, para alcanzar ese esquema abstracto de libre competencia, la competencia de mercado efectiva, lejos de identificarse con el laissez-faire, requiere un conjunto de reglas destinadas a colocar a individuos y empresas al mismo nivel en términos de oportunidades para competir.

El cuarto punto es el énfasis que pone Einaudi en el papel del Estado como entidad económica propiamente dicha, cuya actividad se examina tanto como agente productivo, productor de bienes colectivos, como agente optimizador, orientado a la maximización de ingresos. 45 Su suposición es que las teorías de las finanzas públicas deben utilizar las herramientas analíticas familiares en el estudio del funcionamiento del sector privado. 46Es uno de los principales exponentes de un grupo que creó una “Escuela Fiscalista Italiana” sobre finanzas públicas. Su investigación contribuyó al crecimiento de esta disciplina como rama de la economía, lejos de un enfoque puramente contable, las finanzas públicas tomaron desde diferentes caminos. Por un lado, los economistas keynesianos miraron el problema desde una perspectiva diferente, y con diferentes resultados, basándose en una fuerte intervención proactiva del Estado en la configuración de la economía (las finanzas públicas “funcionales”, bastante alejadas de las de Einaudi “ liberist”vista (véase cap.  5 en este capítulo). por otro lado, también la teoría libertaria de Buchanan de la‘elección pública’, basado en un papel muy limitado del Estado, se ha visto como estrechamente conectada a la escuela italiana (véase Capítulo 4 ). 

## Las dudas de Pigou {-}

La adopción de un concepto ético del liberalismo es, en efecto, necesaria para poner bajo sus alas extendidas las teorías de los economistas que otorgan al Estado un papel central adicional en la configuración del sistema económico. Este rol puede tener diferentes acentos y dimensiones: puede estar relacionado con una alineación de los costos privados y sociales en la producción de bienes y servicios a través de la tributación (como en Pigou), con la gestión macroeconómica (Keynes), con una amplia provisión de servicios a través de gasto público (Beveridge), Esencialmente, el Estado pone remedio a las fallas del mercado, sin su necesaria implicación en la propiedad de los medios de producción, esencia del socialismo. Es preferible la experiencia de la planificación centralizada en lo que sigue siendo una sociedad capitalista, como en la Gran Bretaña de los años treinta, al socialismo real de la Rusia soviética (Pigou); la gestión de la demanda no implica nacionalizaciones (Keynes); la necesidad del socialismo —como propiedad estatal del capital— aún no se ha demostrado (Beveridge). Estos tres pensadores son ejemplos notables de la metamorfosis de una idea que sigue siendo, esencialmente, una idea liberal.

Puede haber cierta renuencia a incluir a Arthur C. Pigou en la lista de pensadores liberales del siglo XX. Por un lado, es ajeno a cualquier especulación de la filosofía social y subraya que su investigación es esencialmente práctica: su impulso no es un impulso filosófico, “el conocimiento por el conocimiento ... ¿Sobre qué base filosófica generalizaciones de este tipo [el leyes de la ciencia económica] resto, aquí no nos preocupamos de indagar ”. La razón de la investigación del economista es “el estudio del comportamiento social de los hombres [que conduce a] resultados prácticos de mejora social”, bajo ciertas circunstancias económicas. Uno está casi tentado a dejar de lado a Pigou cuando se trata de “filosofías económicas”. Además, “expone el argumento de su Economía del bienestaren términos de excepciones a la regla de que el laissez-faire asegura la máxima satisfacción; no cuestionó la regla ”. 47

Por otro lado, sin embargo, está completamente inmerso en esa corriente de pensamiento que no está satisfecho con apoyarse en los esquemas neoclásicos ortodoxos que prevalecen en su entorno de investigación. Su realismo práctico le hace desconfiar de cualquier esquema matemático abstracto, puro y "científico".

Desde esta perspectiva, Pigou “ayudó [ed] a los economistas a convertir molestas controversias políticas en problemas técnicos”. Él —y Keynes— “establecieron a los economistas como un conjunto de herramientas para ser utilizado por los responsables de la formulación de políticas y fueron pioneros en el papel de los asesores económicos del gobierno”. 48

En Cambridge, donde ocupa la cátedra de economía política que perteneció a Alfred Marshall —en una aparente continuidad de hombres y doctrinas— su enfoque realista lo lleva a mirar un “bienestar económico” con ojos diferentes al utilitarismo de esos esquemas. Como Keynes, Pigou se distancia de la economía del laissez-faire. En The Economics of Welfare of 1920 —su obra magna— muestra cierto escepticismo en la suposición optimista según la cual “si solo el gobierno se abstiene de intervenir, automáticamente hará que la tierra, el capital y el trabajo de cualquier país se distribuyan de tal manera que produzcan una producción mayor y, por lo tanto, más bienestar económico que el que podría lograrse con cualquier otro arreglo que no sea el que surge 'naturalmente' ” 49. Incluso si el propio Smith calificó esta libertad natural, al admitir la acción del Estado a las extensiones limitadas, no llegó a partir de darse cuenta de que, Pigou escribe 50 - “el funcionamiento del propio interés es generalmente beneficioso, no debido a una coincidencia natural entre el interés propio de todos y para el bien de todos, sino porque las instituciones humanas están dispuestas de modo que obliguen al interés propio a trabajar en direcciones en las que resulte beneficioso ”. 51

Los editores de la edición 2013 de Palgrave de The Economics of Welfare 52 señalan que es incorrecto asumir este libro como la inspiración intelectual del Estado de Bienestar británico, tal y como se estableció después de la Segunda Guerra Mundial. 53 En este sentido, no hay duda de que Beveridge debe ser visto como su principal engendrador. Pero esa referencia a que las “instituciones humanas” actúan de manera beneficiosa es una apertura a la relevancia que debe darse al interés público, que corrige el interés propio del individuo. ¿Qué hacen (o deberían hacer) estas instituciones?

Pigou relaciona el bienestar económico con el concepto de “dividendo nacional”, por lo que se refiere al total de “servicios objetivos, algunos de los cuales se prestan en forma de mercancías, otros en forma directa”, puestos a disposición del público. Es el volumen de la producción neta corriente: la adición neta a los recursos de la comunidad disponibles para el consumo o para la retención del stock de capital, después de tener en cuenta el despilfarro del stock de capital real existente al inicio de cada período. 54

Sin embargo, la prestación de estos servicios se ve alterada por costos (o beneficios) que no se reflejan en su precio. Las curvas de oferta y demanda específicas de cualquier producto o servicio —en las que se centró la atención de los economistas neoclásicos— no pueden reflejar esos costos (o beneficios). Aquí está su desapego de su maestro, Marshall, y la contribución duradera de su enfoque "práctico": lo que ahora se ve como la extraordinaria actualidad de Pigou es su teoría de los costos y beneficios externos causados ​​por la actividad económica. 55 Estas “externalidades” alteran la relación costo / beneficio, visto solo desde una perspectiva privada. 56 El valor total de una mercancía o un servicio debe desglosarse en dos componentes: valor privado y valor social. 57De esta manera, abandonamos el concepto de valor como relacionado con un bien específico y con un solo agente económico, el valor social debe estar relacionado con toda una comunidad. El valor social mide el costo / beneficio generado por la empresa fuera de sí misma [el ejemplo típico en el discurso actual es la contaminación de las fábricas o, si así lo preferimos, el cambio climático inducido por la industria. Por otro lado, los nuevos bienes digitales, como motores de búsqueda en Internet, tienen beneficios enormes e inconmensurables para los consumidores, un excedente del consumidor 58]. Si la externalidad es un costo, la producción de la empresa es mayor de lo que sería si ese costo externo fuera internalizado; ocurre lo contrario si la externalidad es un beneficio (la producción es menor que en caso contrario). Esta internalización, en ambos casos, alinearía los valores privados y sociales de la producción. Ante la presencia de externalidades, la mejor manera de mitigar las diferencias entre los valores privados y sociales es que el Estado utilice “dispositivos legales coercitivos para dirigir el interés propio hacia los canales sociales”: incentivar la reducción / aumento de las actividades interesadas, y la forma más obvia es la de impuestos / subsidios. 59 Como veremos (Capítulo 4 ), James Buchanan enfrentará el mismo problema desde una perspectiva individualista diferente: por ejemplo, la elección entre contaminación y crecimiento económico por un lado, y un medio ambiente más limpio por el otro, debe exigirse exclusivamente al consenso individual, no a el estado.

Si pensamos en la abrumadora importancia de los problemas relacionados con el medio ambiente en el mundo actual, la contribución de Pigou no puede subestimarse.

Es importante destacar que incluso si el bienestar económico (que es "económico" porque puede medirse con una vara de dinero) no coincide con el bienestar más general, que también se compone de componentes no económicos, es propicio, en un juicio de probabilidad —Para realzar este último. A pesar de la renuencia de Pigou a entrar en el lado filosófico / institucional, la inferencia que se puede hacer de esta conexión es que las instituciones políticas y económicas coherentes con el bienestar general también deben ser coherentes con el bienestar económico (aunque Pigou escribe que su enfoque es una ciencia positiva de lo que es y tiende a ser, pero no normativo, de lo que debería ser. 60El economista no “defiende ni se opone a ningún programa político”. Se podría agregar que el punto de vista de Pigou es una evidencia de la renuencia de algunos economistas a verse a sí mismos como "economistas normativos" en lugar de "científicos positivos").

Por tanto, el velo de la economía es particularmente grueso en la economía de Pigou. Pero su filosofía emerge abiertamente en Socialismo versus capitalismo. 61 ¿Cuál de estos dos sistemas políticos es más propicio para la igualación de los valores sociales y privados de los productos? Comienza con su advertencia habitual: “No es asunto de un economista académico, ni está dentro de su competencia, defender o contra cualquier programa político. Pero es asunto suyo, y debe ser de su competencia, exponer de forma ordenada las consideraciones dominantes, en la medida en que sean económicas, relevantes para el argumento ”. 62El lector no encontrará nada doctrinario en su libro: el materialismo dialéctico marxista o la inevitabilidad del conflicto de clases sociales. Sólo hay cuestiones prácticas: de la distribución de la riqueza y el ingreso, particularmente en presencia de “una clase que vive de la propiedad, que no sólo no necesita trabajar, sino que de hecho no hace nada ... el espectáculo de esta clase es repulsivo para las personas del público espíritu ” 63 ; y de la asignación eficiente de recursos entre diferentes sectores de producción. ¿Es necesario el socialismo para reducir las desigualdades e ineficiencias?

Puso el tema en el contexto de la política británica. Sobre la distribución, señala que si se introdujera el socialismo mediante la confiscación de los medios de producción, el Estado podría asegurar una gran parte de los ingresos que ahora fluyen en gran parte a los ricos, y retenerlos o redistribuirlos entre los pobres, y se reduciría la desigualdad. Pero si el Partido Laborista británico decidiera comprar esos medios a un valor justo, el socialismo no tendría ningún efecto; simplemente, los accionistas se convertirían en rentistas. 64 La tributación, principalmente a través del impuesto sobre la herencia y el impuesto sobre la renta altamente progresivo, sería entonces el instrumento de redistribución; sin embargo, se vería obstaculizado por el temor a dañar la acumulación de capital. Solo un socialismo confiscatorio sería el único remedio efectivo para reparar los ingresos y la riqueza.

Sobre la asignación eficiente de recursos, Pigou utiliza su concepto de externalidades: señala que, bajo el capitalismo, las externalidades de costos, por las cuales los empleadores arrojan parte de sus costos a los de afuera, les permiten producir más de lo que producirían si estos costos fueran internalizados: el costo no es una carga para el empleador. Pero, en la práctica, la evaluación de este costo y de la consiguiente tributación es difícil y una autoridad central de planificación no tendría una ventaja comparativa en este sentido.

En conclusión —dice Pigou— es preferible un concepto vago de socialismo al capitalismo; pero de nuevo de manera pragmática, si tomamos como socialismo el sistema de la Rusia actual, y como capitalismo el sistema británico, donde el capitalismo coexiste con la planificación central socialista, esta última es preferible, sin embargo -agrega- con un uso extensivo de impuestos y una nacionalización de grandes sectores de la industria británica (el Banco de Inglaterra incluyó, por así decirlo, en 1946).

## El liberalismo de Keynes {-}

El librito Economic Philosophy , de Joan Robinson, 65 es un excelente resumen de las premisas ideológicas del liberalismo económico en el siglo XIX, preparando así el escenario para las nuevas “reglas del juego” previstas por la “revolución keynesiana”. “La Teoría General sacó a la luz el problema de la elección y el juicio que los economistas neoclásicos habían logrado sofocar. La ideología para acabar con todas las ideologías se vino abajo. La economía se convirtió una vez más en Economía Política ” 66 …“ Keynes devolvió el problema moral a la economía al destruir la reconciliación neoclásica del egoísmo privado y el servicio público ”. 67

De hecho, está claro que, para Keynes, el aspecto ético es fundamental para la disciplina económica, y esto es suficiente para mantenerla separada de las ciencias naturales. En una carta a Roy Harrod, señala que “En química, física y otras ciencias naturales, el objeto del experimento es completar los valores reales de las diversas cantidades y factores que aparecen en una ecuación o una fórmula; y el trabajo cuando esté hecho es de una vez por todas. En economía este no es el caso y convertir un modelo en una fórmula cuantitativa es destruir su utilidad como instrumento de pensamiento ... la pseudo-analogía con las ciencias físicas lleva directamente en contra del hábito de la mente que es más importante para un economista. propio de adquirir ... se trata de la introspección y de los valores ... de los motivos, las expectativas, la incertidumbre psicológica ”.68

Es interesante observar que las “primeras creencias” de Keynes, remontándose a sus años universitarios, ya muestran un “escape de la tradición benthamita ... fue este escape de Bentham, unido al insuperable individualismo de nuestra filosofía, lo que ha servido para proteger a todos nosotros desde la reducción final ad absurdum del benthamismo conocido como marxismo ” 69 ): un desapego paulatino del pensamiento económico dominante que le llevaría a preguntarse, mucho antes de su Teoría General , si él mismo podría calificarse de“ liberal". 70

En un artículo de 1933 poco citado, 71Keynes escribe: “Fui educado, como la mayoría de los ingleses, para respetar el libre comercio no solo como una doctrina económica que una persona racional e instruida no podría dudar, sino casi como parte de la ley moral ... Sin embargo, la orientación de mi mente es cambiado [y] se modifican mis antecedentes de teoría económica ”. Entonces, escribe, el proteccionismo del siglo XIX no debe verse como una mancha en la eficiencia y el buen sentido (se parece a List). Muchos países (Rusia, Italia, Alemania y, en parte, Estados Unidos y Gran Bretaña) se están embarcando en una variedad de experimentos político-económicos que van más allá de la maximización de beneficios como guía para las decisiones de inversión. Se revaloriza la autosuficiencia nacional y, con ella, protección arancelaria para levantar el desempleo y los controles de capital a fin de evitar que una tasa de interés demasiado alta para atraer inversiones extranjeras vaya en detrimento de las políticas internas. Los viejos liberales pensaban que servirían no sólo a la supervivencia de los más aptos, sino también a “la gran causa de la paz, la gloriosa fertilidad de la mente libre contra las fuerzas del privilegio, el monopolio y la obsolescencia”. Keynes mira más bien con cierta simpatía los nuevos experimentos económicos, el nacionalismo económico, la autosuficiencia, aunque ve tres peligros: la estupidez del doctrinario ("Mussolini quizás está adquiriendo muelas del juicio"), la prisa, la intolerancia. Existe un peligro claro, o casi seguro, de que estas economías no puedan conectarse con la idea liberal, que es la dificultad para aceptar sus políticas sin una conversión al autoritarismo.

Con respecto a la competencia, la visión crítica de Keynes ya se había expresado en El fin del laissez-faire : competencia como “un estado de cosas en el que la distribución ideal de los recursos productivos puede lograrse a través de individuos que actúan de manera independiente mediante el método de prueba y error en tales condiciones. una forma en que los individuos que se mueven en la dirección correcta destruirán mediante la competencia a los que se mueven en la dirección equivocada ... Es un método para llevar a los más exitosos a la cima mediante una lucha despiadada por la supervivencia, que selecciona a los más eficientes por la quiebra de los menos eficientes ” 72 (Esto suena a Rathenau, o Schumpeter. 73 )

Esas nuevas ideas no sólo echaron raíces en países que se estaban moviendo hacia regímenes abiertamente autoritarios, sino que también —como señaló Keynes en su artículo— tuvieron una influencia en países de tradición liberal bien establecida. Sin embargo, en lo que respecta al comercio, el proteccionismo de los Estados Unidos no es nuevo. El país había crecido muy rápido entre el final de la Guerra Civil y 1917 con la ayuda de aranceles estrictos. El atractivo del aislacionismo, después de la Primera Guerra Mundial, fue fuerte. La introducción del arancel Smoot Hawley en 1930 erigió importantes barreras a las importaciones, a pesar de un fuerte superávit comercial. Con respecto al dinero, una postura monetaria muy estricta de la Reserva Federal alentó enormes entradas de capital, sin embargo, esterilizado por el banco central con una política de “dinero administrado” que contrastaba con la “regla del juego” que el patrón oro requería para los países con grandes superávits. El abandono de su paridad oro por la libra esterlina en 1931, y luego por el dólar estadounidense en 1933, marcó el predominio de los intereses nacionalistas y el punto crítico del colapso del patrón oro. El Reino Unido adoptó la Preferencia Imperial en 1932.

Frente a los trastornos económicos masivos y al desempleo, y a los fuertes ataques a la filosofía económica liberal, las reacciones de la disciplina económica fueron dobles: por un lado, la causa principal se vio en una demanda insuficiente de bienes y servicios que el sistema económico es capaz de producir, y por lo tanto en una “falla de mercado”; en el lado opuesto, se atribuyó a las externalidades y la rigidez de los precios un impedimento para que un mercado, por lo demás eficiente, funcionara correctamente. La primera causalidad es la sustancia de la “revolución” macroeconómica keynesiana; este último se queda atrás de una serie de explicaciones que, más allá de las teorías neoclásicas, exploran nuevas vías de un estricto liberalismo económico.

Keynes no tiene nada que objetar a la teoría clásica, dentro de sus propios límites: “Considerada como la teoría de la empresa individual y de la distribución del producto de una determinada cantidad de recursos, la teoría clásica ha hecho una contribución al pensamiento económico que no puede ser impugnada ”. 74 Pero Keynes quiere ir más allá de esos límites, y su Teoría general (1936) es importante, ante todo, por el salto cualitativo que da con respecto a las teorías económicas entonces imperantes, en particular a la teoría neoclásica.

Hemos mencionado anteriormente los dos enfoques neoclásicos principales (walrasiano y marshalliano) para la definición de un equilibrio económico, el primero centrado en el sistema económico general y el segundo en muchos mercados individuales. Ambos muestran que la producción total resulta de la interacción de agentes individuales, movidos por sus utilidades y costos marginales. Keynes pasa de un análisis centrado individualmente al comportamiento agregado de grupos de agentes económicos (consumidores, inversores, rentistas…), cuya demanda no está relacionada con funciones de utilidad individuales. “Es la sustitución de la determinación de precios como tarea esencial de la economía, por la tarea previamente inexistente de determinar el nivel de demanda agregada”. 75El enfoque agregado de Keynes reemplaza al enfoque sumativo para definir el nuevo objeto de la economía. Se pierde la economía “científica”, “pura” (basada en la utilidad marginal, medida matemáticamente). Se recordará que, según Ysidro Edgeworth, el economista neoclásico, “el principio utilitario de que la política debe dirigirse al mayor bien para el mayor número requiere la suma de la felicidad de individuos separados”. 76

La teoría macroeconómica es la rama de la disciplina económica que analiza todo el sistema económico, como una entidad diferente de la suma total de sus componentes individuales. La invención de la macroeconomía requiere insertar la sociedad y su estructura en el estudio de la economía: una convicción compartida tanto por Marx como por Keynes. 77

La nuestra no es una historia del pensamiento económico, nuestro interés se centra en qué filosofía social descansa el pensamiento de Keynes. Sobre este tema, Keynes no fue explícito, y esto puede explicar por qué todavía se le considera, según una opinión, como un colectivista reacio, o como un socialista liberal según otros, o incluso de otras formas. 78 Es de su análisis como economista que Keynes deriva elementos de su filosofía social, y esto ocurre sólo en el capítulo final de su Teoría general. 79 Por tanto, es necesario dedicar algunas palabras a las principales características de su teoría. 80

Los principales problemas de la sociedad en la que vivimos son, según Keynes, la incapacidad de asegurar el pleno empleo y la desigualdad en la distribución de la riqueza y el ingreso. 81Por tanto, Keynes incide en los dos temas fundamentales de la disciplina económica en el siglo XX: la producción y distribución de una determinada producción, con un nuevo énfasis en el segundo. Con respecto al empleo, Keynes escribe que depende de los ingresos que el empresario espera recibir de la producción, que busca maximizar con respecto a sus costos. Por lo tanto, aumenta la producción y el empleo solo en la medida en que el aumento de los costos esté más que compensado por una mayor demanda de los consumidores. Los economistas clásicos piensan que la demanda del consumidor es necesariamente igual al ingreso recibido por los factores de producción empleados por el empresario, de modo que la producción y el empleo pueden expandirse pari passuhasta llegar a una situación de pleno empleo. Pero —observa Keynes— no se consume toda la producción (la propensión a consumir es menor que "uno"). Un crecimiento en el empleo puede ocurrir solo cuando el monto de las inversiones puede absorber el exceso de lo que se produce sobre lo que la comunidad decide consumir.

La demanda de inversiones por parte del empresario no se suma a la demanda de los consumidores de forma que se asegure automáticamente el pleno empleo. La demanda de inversión depende: (1) del rendimiento esperado de la inversión; (2) Sobre su costo, es decir, sobre la tasa de interés. Cuanto menor sea el rendimiento esperado y cuanto mayor sea la tasa de interés, menor será la demanda de inversiones. Esto bien puede estabilizarse en un nivel inferior al que es coherente con el pleno empleo. La demanda agregada, de consumo e inversión, asociada al pleno empleo es, por tanto, “un caso especial, sólo realizado cuando la propensión a consumir y el incentivo a invertir mantienen una relación particular entre sí”, ya sea por accidente o por diseño. Es deber del Estado actuar de manera que esto suceda por diseño, si ese “accidente” no ocurre.

La otra cara del problema es la desigualdad social, “la paradoja de la pobreza en medio de la abundancia”. 82Está relacionada con la diferente propensión a consumir entre las diferentes clases sociales: esta propensión disminuye con el aumento de los ingresos y la riqueza. Los ricos gastan relativamente menos en bienes de consumo. Particularmente en una sociedad que ya es rica, que ya tiene un gran stock de riqueza disponible, esa propensión es relativamente débil, y la debilidad de la demanda del consumidor es un incentivo para reducir la demanda de inversiones: la demanda agregada (para consumo e inversión) es, en consecuencia, bajo, y seguirá una reducción de la producción y el empleo. En resumen, el crecimiento de la inversión y del empleo no depende de una baja propensión a consumir (“lejos de depender de la abstinencia de los ricos”), es decir, de un mayor ahorro, como explican los economistas clásicos, se ve obstaculizado por eso. Hasta que se alcance el pleno empleo,

En el capítulo final de su Teoría general, Keynes pasa a sus "notas de filosofía social". La primera inferencia de su teoría está relacionada con la desigualdad. Esto se ha abordado a través del esquema de tributación directa, que sin embargo ha encontrado severos límites a la evasión tributaria y sobre todo en la opinión — errónea, como se vio anteriormente — de que una alta tributación desalienta la acumulación de ahorros que se considera necesaria para promover las inversiones. “El crecimiento de la riqueza, lejos de depender de la abstinencia de los ricos, como se supone comúnmente, es más probable que se vea obstaculizado por ella”. 83

Su nota de filosofía social es: “Creo que hay una justificación social y psicológica para desigualdades significativas de ingresos y riqueza, pero no para disparidades tan grandes como las que existen hoy. Hay actividades humanas valiosas que requieren el motivo de hacer dinero y el entorno de la propiedad privada de la riqueza para su plena función ... Es mejor que un hombre ejerza una tiranía sobre su saldo bancario que sobre sus conciudadanos ... Pero no es necesario para el estímulo de estas actividades ... que el juego debería jugarse con apuestas tan altas como en la actualidad. Las apuestas mucho más bajas servirán igualmente bien, tan pronto como los jugadores se acostumbren a ellas ”. 84

La segunda inferencia importante, que también tiene consecuencias sobre la distribución de la riqueza, se refiere a la tasa de interés. No es correcto pensar que una tasa alta conduce a mayores inversiones a través de mayores ahorros. Dado que el interés es un factor de costo para el empresario, se realizarán cantidades adicionales de inversión hasta que la eficiencia marginal del capital, definida como el rendimiento esperado de capital adicional, sea igual a la tasa de interés del mercado. 85De ello se deduce que esta tasa debe reducirse hasta el punto en que la rentabilidad esperada implique un nivel de inversión coherente con el pleno empleo. En ese momento, el rendimiento esperado será tan bajo que cubrirá poco más que el desperdicio y la obsolescencia de los instrumentos de capital, y “algún margen para cubrir el riesgo y el ejercicio de la habilidad y el juicio”. La consecuencia social de las bajas tasas de interés está relacionada con sus efectos sobre los inversores. Los ricos que disfrutaron de altos rendimientos de sus ahorros se verán privados de dicha renta, es decir, de una renta que no se obtiene con inversiones de riesgo o con su trabajo: “La eutanasia del rentista”. “Veo el aspecto rentista del capitalismo como una fase de transición que desaparecerá cuando haya hecho su trabajo”. 86

En la teoría económica de Keynes, los determinantes del sistema económico no son el ahorro y la inversión (como sugería la teoría clásica), sino la propensión a consumir, la eficiencia marginal del capital y la tasa de interés. 87Su filosofía económica implica la intervención del gobierno en campos hasta entonces abandonados principalmente a la iniciativa privada, y una ampliación de las funciones tradicionales del Estado, en particular para aumentar la demanda agregada (por influencia de la propensión a consumir e invertir) y a bajar la tasa de interés. , para compatibilizarlos con el objetivo del pleno empleo. Por otro lado, el objetivo de Keynes es salvaguardar las ventajas del individualismo, de la eficiencia económica basada en la descentralización de decisiones y la interacción de los intereses privados, siempre que estas ventajas estén contenidas dentro de los límites antes mencionados. De hecho, cuando gracias a esos “controles centrales” la economía se acerca al pleno empleo, la teoría clásica se vuelve aplicable. Este individualismo libertario sigue siendo importante:88 Y, en lo que respecta a las inversiones, es importante que la intervención del gobierno aborde el volumen de las inversiones, no su dirección (que es decisión de la iniciativa privada: “hay, por supuesto, errores de previsión; pero estos no serían evitado centralizando las decisiones ”. 89 )

Incluso recientemente, Keynes ha sido etiquetado como "planificador". 90 Considerando su filosofía como se describe aquí, esta etiqueta es incorrecta. Una demanda agregada con pleno empleo no implica ni nacionalizaciones, ni orientaciones de producción hacia bienes y servicios específicos, ni fijación de precios fuera de esquemas de mercado. En la Teoría GeneralSe resuelven las propias perplejidades expresadas en su artículo de 1933: la expansión del papel del Estado no llega al colectivismo ni a la planificación; y defiende las elecciones individuales en nombre de la eficiencia y rechaza el autoritarismo en nombre de la libertad. ¿Estamos lejos, quizás, de la frase de Croce, antes mencionada, de que “Para un liberal verdaderamente consciente le suena imposible adherirse a ideales autoritarios y reaccionarios, o comunistas, porque el liberalismo los incluye a todos, dentro de sus límites aceptables”?

Un aspecto del pensamiento keynesiano que merece especial atención está relacionado con las relaciones internacionales. Hoy es recordado como uno de los promotores de la cooperación internacional, organizada bajo la bandera del Sistema de Bretton Woods. Pero es necesario mencionar una actitud nacionalista, como reacción al colapso del orden internacional del patrón oro, actitud que enfatiza la capacidad reactiva de su propio país ante la Gran Depresión e incluso lo acerca a ideas mercantilistas. Hay un aspecto, no enfatizado, en la visión de Keynes: su acento en el carácter doméstico de sus propuestas, que es complementario a su rechazo del patrón oro. No es casualidad que, en el capítulo 23 de la Teoría generaltitulado Notas sobre mercantilismo, recuerda, en analogía a lo que Friedrich List había escrito un siglo antes, cuatro puntos: (1) “El pensamiento mercantilista nunca supuso que hubiera una tendencia autoajustable por la cual la tasa de interés se establecería al nivel apropiado, más bien pensando que una tasa de interés indebidamente alta era el principal obstáculo para el crecimiento de la riqueza ”; (2) “Los mercantilistas eran conscientes de la falacia de la baratura y del peligro de que la competencia excesiva pueda volver los términos de intercambio en contra de un país”, de ahí la protección del mercado interno; (3) “El deseo del individuo de aumentar su riqueza personal absteniéndose del consumo ha sido generalmente más fuerte que el incentivo al empresario de aumentar la riqueza nacional empleando mano de obra en la construcción de activos duraderos”, de ahí la necesidad de bajar la tasa de interés; (4) los mercantilistas eran conscientes de que el proteccionismo podría llevar a la guerra, pero —escribe Keynes— “su realismo es mucho preferible al pensamiento confuso de los defensores contemporáneos de un patrón oro fijado internacionalmente y del laissez-faire en los préstamos internacionales, que creen que es precisamente estas políticas que mejor promoverán la paz ”.91

Keynes, en resumen, no duda en criticar las “teorías defectuosas” de la City de Londres, cuando piensan que para mantener la rígida paridad de las divisas —es decir, para mantener el equilibrio de las cuentas exteriores— la “tasa bancaria”, si es necesario, debe ajustarse al alza, hasta niveles totalmente incompatibles con el pleno empleo. 92 Los partidarios del patrón oro no se inmutaron. “Pero el señor Keynes ni siquiera insistiría en una estabilización de las divisas. Si tuviera que elegir entre una fluctuación en el nivel de precios y una fluctuación en las divisas, optaría por la última ”. 93

Sin embargo, la convivencia del liberalismo internacional y el interés nacional no había sido un problema hasta que Gran Bretaña fue el director de la orquesta internacional, pero las cosas cambiaron cuando la batuta pasó a manos estadounidenses. Sólo durante la Segunda Guerra Mundial Keynes avanzó hacia la idea de una unión de compensación multilateral que superaría las dificultades y complicaciones de un gran número de acuerdos bilaterales (con Gran Bretaña en el centro de su Imperio); tendría una institución supranacional como cámara de compensación central; se basaría en una nueva unidad monetaria internacional, el "bancor", que la cámara de compensación emitirá a los países miembros contra el pago de cuotas en oro y monedas nacionales. Este esquema chocaría en Bretton Woods con las políticas centradas en el dólar del estadounidense Dexter White,94 Como sabemos, no se creó una unidad monetaria internacional, el dólar ocupó el lugar como la principal moneda de reserva y el sistema de Bretton Woods permaneció inherentemente inestable. La posición de superávit, y luego deudor, del país hegemónico, Estados Unidos, tuvo como consecuencia escasez y luego exceso de liquidez internacional y transmitió presiones deflacionarias y luego inflacionarias sobre el resto del mundo, hasta su finalización. fallecimiento en 1971.

Estas consideraciones muestran cuán débil es la frontera entre una visión basada en un liberalismo global y otra basada en el interés nacional, y cómo un liberal puede encontrar difícil conciliar las dos visiones en diversas circunstancias. En nuestro caso, la conciencia, madurada después de la Primera Guerra, de que el papel hegemónico de Gran Bretaña había llegado inexorablemente a su fin, empujó a Keynes a elaborar un sistema de cooperación internacional que pudiera contrarrestar la hegemonía estadounidense entrante.

## Estado de bienestar de Beveridge {-}

Aún más que en Keynes, es en las obras de Beveridge donde se persigue una visión más amplia del papel del Estado. Es evidente de inmediato que la atención de Beveridge va más allá de los límites de la economía y toca las características esenciales de un Estado liberal. El objetivo del pleno empleo debe ir acompañado de la condición de que se conserven todas las libertades esenciales, y solo un gobierno democrático puede mantener y defender lo que él considera libertades esenciales de los ciudadanos: libertad de escritura, estudio y enseñanza; libertad de reunión con fines políticos y de otro tipo; libertad de elección de ocupación; y libertad en la gestión de los ingresos personales. Es deber del Estado implementarlos. Por lo tanto, esta larga lista significa excluir cualquier solución totalitaria de pleno empleo en una sociedad completamente planificada y reglamentada por un “dictador inamovible”: la necesidad del socialismo aún no se ha demostrado, dice Beveridge. Pero, de manera significativa, no incluye, en estas libertades esenciales, la de la propiedad privada de los medios de producción: si la experiencia mostrara que la abolición de la propiedad privada es necesaria para el pleno empleo, esta abolición tendría que emprenderse.95 Un Estado liberal no estaría necesariamente en conflicto con una estructura productiva de propiedad pública (podemos recordar en este punto el liberalismo ético de Croce y la coincidencia no necesaria del liberalismo económico y ético).

Para hacer efectivas esas libertades, no una simple declaración de intenciones, el Estado debe brindar no solo servicios públicos bien establecidos como defensa o policía o justicia, sino también otros servicios como educación gratuita, seguridad social, servicio nacional de salud, infraestructuras. 96

Las finanzas públicas, según Beveridge, tienen una variedad de subfunciones: generar una distorsión de los recursos para la satisfacción de los deseos públicos (un objetivo reconocido también por los economistas clásicos, pero ampliado por Beveridge al ampliar la lista de servicios que le corresponde a la Estado a proporcionar); corregir la distribución de la renta y la riqueza; utilizar el instrumento fiscal para la estabilización del ingreso y el crecimiento: el aspecto distributivo parece tener prioridad sobre el crecimiento (esto es el llamado “financiamiento funcional”, ver más abajo). Incluso un gasto público improductivo, que sin embargo genera empleo, es preferible a una mano de obra obligada a la ociosidad. Pertenece a Beveridge la frase, a veces atribuida a Keynes, de que “es mejor emplear personas para cavar agujeros y rellenarlos de nuevo, que no emplearlos en absoluto”.97

Hasta ahora —observa Beveridge— dos principios fundamentales han regido el presupuesto del Estado: mantener el gasto estatal en el mínimo necesario para satisfacer necesidades ineludibles y equilibrar los ingresos y los desembolsos de cada año. Para el logro de esos objetivos más amplios de asegurar la satisfacción de los deseos públicos en un marco de pleno empleo, Beveridge piensa que el presupuesto público debe interpretarse determinando “no sólo los ingresos y gastos del gobierno, sino los ingresos y egresos estimados de la nación como entero". 98Beveridge es keynesiano, porque según ambos el Estado es el último responsable del nivel de los desembolsos totales (la “demanda efectiva” keynesiana) —privada y pública— consistente con una situación de pleno empleo. Beveridge reconoce que se necesitan presupuestos públicos más grandes, porque el gasto total, público y privado, para el consumo o la inversión: la renta nacional debe ser igual a la cantidad necesaria para asegurar que la mano de obra esté plenamente empleada. 99 Dentro de este marco macroeconómico, establece tres reglas de las finanzas nacionales, en orden de prioridad: los desembolsos deben dirigirse al pleno empleo; deben estar dirigidos por prioridades sociales, como se indicó anteriormente; sujeto a la primera y segunda prioridad, es mejor proporcionar medios para los desembolsos mediante impuestos que mediante préstamos. 100Incluso admitiendo déficits públicos cuando es necesario, Beveridge se muestra reacio a alentarlos, porque el endeudamiento público significa aumentar los ingresos y la riqueza de los rentistas: personas que tienen reclamos contra la comunidad sin contribuir con su propio trabajo. 101 Aquí, Beveridge parece olvidar que una cantidad cada vez mayor de deuda pública estaba en manos de la clase trabajadora, que está lejos de ser definida como "rentistas".

En resumen, las ideas de Beveridge y las “finanzas funcionales” cuyos principios desarrollaría Abba Lerner 102 tienen implicaciones más amplias que el gasto deficitario de Keynes, porque tienen un impacto profundo en la estructura y funcionamiento del sistema económico. Las políticas económicas de la posguerra se sienten probablemente más influidas por Beveridge que por Keynes. Y Beveridge, más que Keynes, podría ser visto como el principal objetivo de las críticas de los economistas radicalmente libertarios, y aún más de los ordoliberalistas alemanes (véanse las Secciones  6 , 7 y 8 de este capítulo).

Lerner representa un paso más hacia la ampliación del sector público. Afirmó, al comienzo de su Economía del control , 103ese control significa la aplicación deliberada de cualquier política que sirva mejor a la intención social, sin prejuzgar la cuestión entre la propiedad colectiva y la administración o alguna forma de empresa privada. Tres cuestiones están ante la economía de control para resolver: el empleo, el monopolio y la distribución de la renta. Hay dogmas tanto de la derecha (el gobierno que no interfiere con los negocios con fines de lucro) como de la izquierda, que establecerían el 100% del colectivismo y prohibirían cualquier empresa privada con fines de lucro como inmoral; pero una economía de control puede cosechar los beneficios de la economía capitalista y la economía colectivista, y la economía del bienestar resultante reconciliará el liberalismo y el socialismo. 104

El fuerte internacionalismo de Beveridge es visible en una cortés controversia entre él y Keynes que se remonta al período de la Gran Depresión, cuando ambos participaron, en 1931, en un ciclo de conferencias sobre La crisis económica mundial y la vía de escape. 105 Keynes había invocado la adopción, por parte del Reino Unido, de un arancel protector, porque -dijo- “es un previo necesario para la recuperación mundial que este país recupere su libertad de acción y su poder de iniciativa internacional”. 106La respuesta de Beveridge acusó a Keynes de nacionalismo, basado en la pretensión británica de actuar como líder. “Bueno - dijo Beveridge - me inclino a estar de acuerdo en que nosotros [los británicos] somos [los líderes] ... Pero si la justificación para fortalecernos es que somos mejores internacionalistas, para fortalecernos, ... imitando el nacionalismo tonto de los demás, destruye esa justificación ”. 107

Las metamorfosis del liberalismo en el siglo XX muestran que una de sus principales características, el “cosmopolitismo” (globalismo), puede perderse o, en cierta medida, debilitarse. Las influencias nacionalistas o socialistas surgen según diferentes circunstancias. Con Beveridge, lo que parece prevalecer es una idea del liberalismo como concepto ético ante cualquier implicación de eficiencia económica. Esta idea supone una intervención activa del Estado para alcanzar objetivos como el pleno empleo y la prestación de una serie ampliada de servicios públicos. Sin estos objetivos, la libertad sería un concepto vacío, no podría concretarse.

## La escuela austriaca y el liberalismo de Hayek {-}

“No hay nada en los principios básicos del liberalismo que lo convierta en un credo estacionario —escribe Hayek—, no hay reglas estrictas fijadas de una vez por todas. El principio fundamental de que en el ordenamiento de nuestros asuntos debemos aprovechar al máximo las fuerzas espontáneas de la sociedad y recurrir lo menos posible a la coacción, tiene una infinita variedad de aplicaciones ”. 108

Esta frase es evidencia de lo que hemos subrayado al comienzo de este capítulo: las metamorfosis del liberalismo en el siglo XX. De hecho, la Primera Guerra Mundial, la crisis de Wall Street, la Gran Depresión y los desarrollos sociales y políticos relacionados, incluso las nuevas tendencias en el pensamiento filosófico que separaron los conceptos de liberalismo ético y económico, fueron razones para un gran replanteamiento del bien. -visiones económicas establecidas. Pero no todas las reflexiones iban en la misma dirección: desde luego, no todos en la dirección descrita en los apartados anteriores (en particular, 3 - 5) de este capítulo. A diferencia de los autores que acabamos de mencionar (Keynes, Beveridge o incluso Pigou), otros pensadores liberales reaccionaron a las crisis políticas y al colapso de las principales economías con igual escepticismo hacia ambas ideas de una amplia participación del Estado en la conducción de la actividad económica ( que fue criticado como un socialismo progresivo antilibertario), y las ideologías totalitarias, poniendo en pie de igualdad el nacionalismo fascista y el socialismo marxista. El mejor epítome de esta visión está representado por lo que generalmente se identifica como la Escuela Austriaca y la Escuela Americana de Chicago. Los defensores de ambos estuvieron bien representados en la Sociedad Mont Pèlerin, una organización creada en 1947, para elaborar principios destinados a crear y preservar una sociedad libre. El ordoliberalismo alemán merece una mención distinta, por sus peculiaridades.

No hemos mencionado en el primer capítulo al economista político que a menudo se incluye, con Jevons y Walras, entre los tres principales representantes de la teoría de la utilidad marginal, el austriaco Carl Menger. 109 La razón es que Menger ocupa una posición peculiar, siendo al mismo tiempo un exponente importante de la escuela neoclásica y el engendrador de una corriente de pensamiento bastante diferente, la Escuela Austriaca de Economía. Como intentaremos aclarar, aparece más como un hijo rebelde del historicismo alemán que como una expresión de la nueva ciencia positiva en el campo de la economía. 110

Es el momento de mencionarlo ahora, como el iniciador de esa Escuela Austriaca, que se desarrolló en el siglo XX, teniendo a Hayek como probablemente su mayor exponente, y dio un renovado prestigio moral al liberalismo económico. En esta Escuela se incluye un grupo de economistas “liberales” que comprende, además de Hayek, autores como O. Morgenstern, F. Machlup, G. von Haberler, P. Rosenstein Rodan, L. von Mises: economistas de origen austriaco o centroeuropeo , quienes, debido a sus ideas, se trasladaron principalmente a Estados Unidos o Gran Bretaña.

Menger, con Jevons y Walras, reaccionó contra la Escuela Clásica (mayoritariamente británica) de Smith o Ricardo. 111 Como sabemos, la Escuela Clásica apoyó la visión de una teoría objetiva del valor trabajo y no dio relevancia a la teoría subjetiva de la utilidad individual. “Una de las razones por las que las doctrinas clásicas nunca se habían establecido firmemente en Alemania era que los economistas alemanes siempre habían sido conscientes de ciertas contradicciones inherentes a cualquier teoría del valor del costo o del trabajo” 112(la teoría ricardiana). Menger se centró en cambio en el individuo y su utilidad, contribuyendo así a construir su propia versión del marginalismo. El camino de Menger hacia el marginalismo fue, sin embargo, diferente al de los economistas neoclásicos, y no puede explicarse sin considerar su origen cultural: él, licenciado en Derecho en Viena y Cracovia, tuvo que liberarse en primer lugar de los esquemas de la Historia. Escuela de Economía, entonces imperante en Alemania.

Es bien conocido el duro debate de Menger con el director de la Escuela Histórica, Gustav Schmoller. Schmoller criticó a Menger porque, en su opinión, Menger no hizo más que repetir la “ficción errónea y obsoleta” de los economistas del libre comercio británicos: un método deductivo basado en la asunción de proposiciones elementales sobre un hombre abstracto y medio. 113Menger reaccionó a Schmoller: el error de la Escuela Histórica fue que consideraba la economía nacional, que es un complejo de economías individuales individuales, como, en sí misma, un abstracto, "un todo": una gran economía en la que la nación debe representar en sí mismo como sujeto productor y consumidor. En cambio, el desarrollo de un sistema económico debería verse, según Menger, como el resultado involuntario del comportamiento de varios individuos que operan en su propio interés.

Habiendo descrito a Menger como un antagonista tanto de la Escuela Clásica (en su mayoría británica) como de la Escuela Histórica Alemana, queda por ver por qué aparece como una figura peculiar también entre los economistas neoclásicos. Como ellos, confiaba en la utilidad individual como una medida subjetiva de valor: exactamente lo que estaban haciendo los economistas neoclásicos en otros lugares. Pero al mismo tiempo, Menger adoptó una posición bien caracterizada.

Se ha observado que, a diferencia de Jevons y Walras, Menger favoreció un enfoque humanista 114que no les pertenece. No nos detendremos en su teoría que, al igual que otros escritores neoclásicos, se centra en una idea subjetiva del valor, en el análisis marginal, en el individualismo metodológico; pero su enfoque también se centra en la elección humana intencionada, en el acto de preferencia como juicio y en la relación entre medios y fines. Jevons y Walras rechazaron la relación medios-fines, en lugar de favorecer la técnica de modelar relaciones complejas como sistemas de ecuaciones simultáneas en las que ninguna variable es causa de otra variable. Menger vio en cambio, a través de la relación causal de medios y fines, la estructura temporal de la producción: el elemento del tiempo había sido descuidado por los economistas neoclásicos,115 )

La Escuela Austriaca de Economía se desarrolló en el siglo XX, consolidando su propia postura en el campo cada vez más diversificado del liberalismo y oponiéndose a diferentes puntos de vista liberales, como keynesianos. Esta Escuela agregó vitalidad a la idea liberal a través de un credo radicalmente libertario, donde un tipo específico de ética (de una manera similar a la visión de Einaudi, como se describió anteriormente) sigue siendo un componente básico.

Friedrich von Hayek puede considerarse el principal exponente de este tipo de liberalismo del siglo XX. En oposición a los economistas neoclásicos y a su padre natural, el positivismo, se distancia de su postura "científica" al hacer una revalorización explícita de la "ideología", que él ve "simplemente [como] el análisis de las ideas y acciones humanas ”. No es casualidad que haya escrito una nueva y hermosa Introducción a los Principios de Economía de Menger .

Hayek hace una fuerte contraposición de las ciencias sociales y naturales, justo lo contrario de los seguidores de la filosofía positivista. Los primeros no tratan de las relaciones entre las cosas, sino de las relaciones entre el hombre y las cosas, o las relaciones entre el hombre y el hombre. Su objetivo es explicar los resultados no deseados o no deseados de las acciones de muchos hombres. Estas acciones -tal como las estudian las ciencias sociales en sentido estricto (solían ser descritas -escribe- como las ciencias morales) - son, de manera consciente o reflexiva, llevadas a cabo por el individuo cuando tiene que elegir entre varios cursos abiertos. a él. El enfoque de las ciencias naturales es objetivo, el de las ciencias sociales y morales es subjetivo y los “hechos” de las ciencias naturales se convierten —dentro de las ciencias sociales— en “opiniones, ideas, conceptos”. Como hemos visto en el capítulo 1 Hayek, en su actitud polémica hacia el positivismo, llega a asimilar a Comte a Hegel, en su postura anti-libertaria, incluso colocando a Comte por debajo del Hegel oscurantista. 116 Este dúo poco acogedor, que se basa en leyes simples para explicar la realidad, lo completa Marx, que se basa en ambos: Comte: leyes naturales; Hegel: principios metafísicos; Marx: interpretación materialista. 117

Dentro del marco de su actitud en gran parte anti-positivista, hay al menos dos elementos que diferencian la visión de Hayek de la de los economistas neoclásicos: (a) un enfoque teórico diferente del concepto de racionalidad en economía; yb) el papel del Estado en un contexto social, político y económico en evolución.

Sobre el primer punto, relativo a la racionalidad, Hayek se distanció de los marginalistas neoclásicos y negó que un orden económico racional resulte del supuesto de que poseemos toda la información relevante, podemos formular un sistema racional de preferencias y conocer los medios disponibles. para ponerlos en práctica. Si este fuera el caso, la solución óptima para la mejor utilización de los recursos disponibles (trabajo, capital, tierra) sería, de hecho, solo una deducción lógica, mejor expresada en forma matemática. Sin embargo, estas condiciones para un orden racional no existen en realidad, ya que sólo hemos "fragmentados fragmentos de conocimiento incompleto y frecuentemente contradictorio", "el conocimiento de las circunstancias particulares de tiempo y lugar". 118¿Cómo utilizar este “conocimiento que no se le da a nadie en su totalidad”? Según Hayek, el mercado libre es el arreglo económico más eficiente, no porque cada agente económico tenga un programa completo y racional de cualquier comportamiento alternativo posible (la incertidumbre es inevitable), sino porque los conocimientos parciales dispersos están conectados por el sistema de precios. . El mercado proporciona la conexión necesaria entre los agentes económicos y los precios son una información objetiva sobre los recursos disponibles. En el mercado, se crea un pedido espontáneo.

El rechazo de una autoridad de planificación es el sequitur necesario : al ser las preferencias individuales poco claras e incognoscibles, la autoridad no puede utilizar ninguna información sobre ellas para gobernar la economía en una determinada dirección. Un plan central está destinado al fracaso porque ningún vehículo puede transmitir a la autoridad lo que es, per se , incierto y cambiante.

La formación del precio correcto requiere un sistema basado en la competencia. Y esto, a su vez, requiere un papel para el Estado: este es el segundo elemento de diferencia con los economistas neoclásicos. Al papel del Estado —como garante de la competencia más que como planificador central— Hayek dedica gran parte de The Road to Serfdom. 119No rechaza la idea de planificación si se refiere al agente económico único, es decir, si significa emplear la previsión y el pensamiento sistemático en la planificación de los asuntos comunes del hombre, sino la tarea del "poseedor del poder coercitivo" (el Estado). se limita a crear condiciones que permitan al individuo planificar con éxito. El pensador liberal está a favor de hacer el mejor uso posible de las fuerzas de la competencia como medio para mejorar la planificación individual, es decir, para coordinar los esfuerzos humanos.

La competencia, subraya, no es seguir un laissez-faire dogmático: Hayek reconoce que la estructura de la sociedad ha cambiado drásticamente con respecto al siglo XIX. El laissez-faire debe verse en un contexto histórico y como una regla empírica, basada como está en una aceptación pasiva de las instituciones como son, como una “regla cruda” en la que se expresaron los principios de la política económica del siglo XIX. . Pero esos principios fueron "sólo el comienzo", y seguir confiando en esa regla práctica ha hecho mucho daño a la causa liberal. Hay espacio para una mejora gradual del marco institucional de una sociedad libre. El problema —añade Hayek— es que este avance ha sido lento: ahora hay un campo amplio e incuestionable de actividad estatal.

“El funcionamiento de una competencia no solo requiere una adecuada organización de ciertas instituciones como los mercados de dinero y canales de información, algunos de los cuales nunca pueden ser proporcionados por empresas privadas, sino que depende, sobre todo, de la existencia de un sistema legal adecuado ... diseñado tanto para preservar la competencia como para que funcione de la manera más beneficiosa posible. De ninguna manera es suficiente que la ley reconozca el principio de propiedad privada y libertad de contratación; mucho depende de la definición precisa del derecho de propiedad aplicado a diferentes cosas ”. 120 La competencia definida en esta línea implica que no se puede permitir ningún tipo de acuerdo de organización sindicalista o “corporativa” de la industria: un estado de cosas, un monopolio, correctamente opuesto tanto por liberales como por socialistas.121

El Camino de servidumbre de Hayek fue escrito durante la Segunda Guerra Mundial, bajo el impulso de los desarrollos políticos y militares, incluso si es el resultado de trabajos anteriores. 122 Evidentemente se ve afectado por ese clima específico, por la enorme presión proveniente de los estados totalitarios; es una mezcla de reflexiones teóricas e históricas e incitaciones a volver al "camino abandonado" del liberalismo de Adam Smith, Hume, Locke, y al individualismo de Cicerón, Erasmo, Montaigne, apoyándose en las fuerzas espontáneas de la sociedad, contra cualquier forma de coerción. 123Esta ideología estrictamente libertaria y de libre mercado es una guía para Hayek para reflexionar sobre los temas de “planificación y democracia” y “planificación y Estado de derecho”. Y es igualmente duro con las economías "occidentales" y totalitarias. Analicemos estos dos temas.

Sobre planificación y democracia, la afirmación fundamental de Hayek es que “la democracia es esencialmente un medio, un dispositivo utilitario para salvaguardar la paz interna y la libertad individual”: un dispositivo instrumental, ya que no reconoce a la sociedad y el bien público como la pieza central de la democracia. El objetivo social colectivista, el bienestar general, se realiza a través de un plan único, mediante el cual cada necesidad individual recibe un cierto rango, en una escala de valores definida por el planificador, que es una especie de código ético completo. Un código ético común lo suficientemente amplio como para incluir un plan económico unitario es una inversión de la tendencia a avanzar hacia una ampliación de la esfera de la libertad individual. Este código no solo sería inconveniente desde el punto de vista de la libertad individual,124

Hayek sigue un enfoque benthamita de la utilidad cuando escribe que la filosofía del individualismo no asume que el hombre es egoísta o egoísta, sino simplemente que tiene su propia escala de valores, que no debería estar sujeta a ningún dictado de otros. 125Esta visión está comprensiblemente en curso de colisión con el sistema colectivista, definido como "la organización deliberada de los trabajos de la sociedad para un objetivo social definido". Los tipos de colectivismo, ya sean fascismo o comunismo, pueden diferenciarse por la naturaleza de tal objetivo, pero cualquier colectivismo es diferente del liberalismo y el individualismo en su negativa a reconocer una esfera de autonomía donde los fines individuales son supremos. Desde 1931 [la Depresión] —lamenta — Estados Unidos y Gran Bretaña — "Occidente" — se han movido lentamente hacia el socialismo (esta es una crítica severa de los economistas liberales mencionados anteriormente), aunque sabemos que socialismo significa, en el fin, esclavitud. 126

Hayek fija entonces un concepto fundamental de Estado liberal: el Estado de derecho, en contraposición al gobierno arbitrario. En virtud del Estado de derecho, “el gobierno se limita a fijar reglas que determinen las condiciones en las que se pueden utilizar los recursos disponibles, dejando a las personas la decisión de los fines con los que se utilizarán”. 127 Las reglas se establecen de antemano, como reglas formales destinadas a ser meramente instrumentales en la búsqueda de los diversos fines individuales de las personas. En consecuencia, la discrecionalidad dejada al Poder Ejecutivo del gobierno que ejerce poderes coercitivos se reduce tanto como sea posible.

En el extremo opuesto está el gobierno arbitrario, por el cual el gobierno dirige el uso de los medios de producción a sus fines particulares, a través de reglas sustantivas y siempre provisionales. El gobierno atiende las necesidades reales de las personas y elige entre ellas, según las circunstancias a medida que surgen. Como ejemplo de gobierno arbitrario, Hayek toma el caso de la Alemania nazi 128 : Los nazis siempre han sido intolerantes con una justicia meramente formal, con el Estado de derecho, es decir, con una ley que no tiene una visión de lo bien que deberían estar determinadas personas. ser y querer una socialización de la ley, atacando la independencia de los jueces e invocando la Freirechtsshule. 129 En la Alemania nazi, el Estado Gerechte (el Estado justo), defendido por el jurista Carl Schmitt,130 es el sustituto del Estado de derecho.

Es cierto, señala Hayek, que el Estado de derecho tolera las desigualdades económicas. Pero, en una especie de compensación entre desigualdad y pérdida de libertad individual, el péndulo de Hayek se inclina hacia el primero. En su apasionada defensa de la libertad individual y la aversión al bienestar colectivista, llega a reconocer que los valores económicos son menos importantes para nosotros que muchas cosas precisamente porque en materia económica somos libres de decidir lo que consideramos marginal ... la planificación implicaría la dirección de casi la totalidad de nuestra vida. 131 Esta notación de Hayek da la esencia del Estado liberal, que debe dar libertad a los ciudadanos para elegir, no solo [y no tanto, se podría agregar] en sus elecciones económicas, sino más importantemente en cualquier aspecto de la vida privada y pública, cuando hay que tomar una decisión.

Mientras que un punto de vista croceano podría inducir a pensar que un liberalismo ético puede coexistir con estructuras económicas no liberales (ver arriba), Hayek está fuertemente en contra de la posibilidad de que la democracia pueda sobrevivir si los asuntos económicos fueran dirigidos por una autoridad superior. En este sentido, se puede decir con seguridad que, tanto con Hayek como con Luigi Einaudi, no se puede distinguir el liberalismo ético, económico y político, son solo una idea: una posición que los pone en la corriente del pensamiento que se remonta a el liberalismo del siglo XIX, y toma la forma de un libertarismo que abre una amplia brecha entre ellos y el liberalismo de Keynes o Beveridge.

Hayek hace una observación aguda para motivar el surgimiento del totalitarismo de extrema derecha, de la actual amenaza fascista-nazi. Señala que la teoría socialista, marxista o no, está dominada por la idea de una división de la sociedad en dos clases con intereses comunes pero mutuamente opuestos: capitalistas y trabajadores industriales. Esta contraposición binaria la hacen los socialistas en el supuesto de que la clase media desaparecería. Pero, según Hayek, los socialistas han hecho caso omiso del surgimiento de una clase media nueva y muy grande (compuesta por empleados, trabajadores administrativos, comerciantes, pequeños funcionarios). Contrariamente a las expectativas de los socialistas, esta nueva clase media, la pequeña burguesía, sobrevivió y ganó fuerza, a pesar de que su posición económica se estaba deteriorando frente a los trabajadores industriales. Ambas clases, obreros industriales y pequeña burguesía, estaban asociadas por un odio compartido al sistema capitalista, y en este sentido, según Hayek, ambas eran socialistas, pero los ideales revolucionarios no tenían atractivo para esta clase media, su idea de la justicia era diferente a la del viejo socialismo. El fascismo y el nacionalsocialismo —el resultado político del odio de la clase pequeñoburguesa al capitalismo liberal— son una especie de socialismo de clase media. El conflicto entre estos movimientos políticos, por un lado, y el viejo socialismo, por el otro, debe verse como un conflicto de facciones socialistas rivales. su idea de justicia era diferente a la del viejo socialismo. El fascismo y el nacionalsocialismo —el resultado político del odio de la clase pequeñoburguesa al capitalismo liberal— son una especie de socialismo de clase media. El conflicto entre estos movimientos políticos, por un lado, y el viejo socialismo, por el otro, debe verse como un conflicto de facciones socialistas rivales. su idea de justicia era diferente a la del viejo socialismo. El fascismo y el nacionalsocialismo —el resultado político del odio de la clase pequeñoburguesa al capitalismo liberal— son una especie de socialismo de clase media. El conflicto entre estos movimientos políticos, por un lado, y el viejo socialismo, por el otro, debe verse como un conflicto de facciones socialistas rivales.132

Esta visión de Hayek, por singular que parezca, puede compararse con los comentarios de Marx sobre la pequeña burguesía: ambos escritores comprenden plenamente la relevancia social y económica de esta clase. Marx lo vio como reaccionario, adverso al socialismo y estaba convencido de que finalmente desaparecería (ver Capítulo 1 ); Hayek, por el contrario, ve a esta clase como fortaleciéndose y ganando poder, y como una nueva facción rival del socialismo mismo. Sin duda, Hayek tenía razón al subrayar la importancia no transitoria de la pequeña burguesía y su ideología totalitaria no liberal, pero su asimilación de esta ideología al socialismo puede ser discutible, si por socialismo pretendemos un derrocamiento revolucionario de la clase capitalista. 

## La escuela de Chicago {-}

La "vieja" escuela de Chicago ha sido opacada durante mucho tiempo por la "nueva escuela", la defendida por Milton Friedman y George Stigler, quienes vieron la vieja escuela como "intervencionista", siendo su teoría caracterizada por un conjunto firme de reglas, con que el mercado y sus participantes deben cumplir. Según el Antiguo, la función apropiada del Estado no es prestar servicios ni realizar algunas actividades económicas, sino dar un marco de reglas dentro del cual las actividades económicas de los agentes económicos públicos y privados puedan desarrollarse libremente. Uno de sus principales exponentes, Henry Simons, afirma explícitamente que el suyo es “un esquema coherente de ética práctica, una filosofía político-económica o, si se quiere, una posición ideológica bien definida… libertaria o, en el inglés-continental sentido, liberal ”.133 Simons también presta atención al aspecto distributivo del sistema económico, que sin embargo se resuelve en lo que él llama —al igual que Walras— justicia conmutativa 134 : “cada uno recibirá según contribuya (o contribuya) a la producción organizada, cooperativa y conjunta , o en lenguaje técnico económico según la productividad de su propiedad, capital o capacidad (incluida la capacidad personal) ”. 135

Simons da por sentada su oposición al comunismo y al fascismo, pero los verdaderos enemigos de sus ideas son "nuestros reformadores liberales e intelectuales políticamente ambiciosos ... los defensores ingenuos de la economía dirigida o la planificación nacional" (no es difícil identificar a estos reformadores como el Nuevo Distribuidores). 136 “Es una responsabilidad obvia del Estado ... mantener el tipo de marco legal e institucional dentro del cual la competencia puede funcionar efectivamente como una agencia de control ... el llamado fracaso del capitalismo (del sistema de libre empresa, de competencia) puede razonablemente ser interpretado principalmente como un fracaso del Estado político en el cumplimiento de sus responsabilidades mínimas bajo el capitalismo ”. 137La responsabilidad de las fluctuaciones económicas pertenece al Estado que desestabiliza el sistema económico al expandir y contraer la cantidad de dinero en circulación (el lado monetario de la teoría de Simons se considerará más adelante).

Con los "defensores ingenuos de la economía gestionada o la planificación nacional ... debemos estar de acuerdo en un punto vital, a saber, que ahora existe una necesidad imperiosa de un programa de legislación económica sólido y positivo". 138 Sin embargo, este programa va en contra de las políticas de los New Dealers: la legislación debe establecer que el gobierno tiene pocas funciones: mantener el orden interno, hacer la guerra, promover el libre comercio frente a cualquier forma de mercantilismo. A las conocidas libertades rooseveltianas —la libertad de expresión, de culto, de la miseria, del miedo— sólo hay que añadir una: la libertad de empresa, mediante la minimización de las responsabilidades del Estado. 139

“Los objetivos próximos de una política económica tradicionalmente liberal, en las condiciones modernas, pueden definirse en términos de los problemas: primero, del dinero; segundo, de monopolio y regulación; y, tercero, de la desigualdad ”. 140

Acerca del dinero, la creciente atención de Simons, y muchos otros, es el signo obvio de la dificultad de reemplazar el antiguo patrón oro con nuevos arreglos monetarios, dadas las implicaciones sociales y políticas de un “dinero sólido”. La administración del dinero implica reglas de juego estables bien definidas por la ley, destinadas a controlar el dinero en cantidad y valor, mientras que cualquier discreción en la administración del dinero debe rechazarse. Estas reglas deberían ser una especie de mandato extraconstitucional o cuasi constitucional. También requerirían una reforma del sistema bancario, que debería separar la función monetaria (que es de carácter público) de la “movilización de fondos para fines de inversión”, es decir, del crédito (que es un negocio privado). 141

Las reglas monetarias también deben afectar la política fiscal, porque es a través de ella que se mejoran; en otras palabras, la política fiscal no debería desestabilizar el dinero. Como consecuencia, Simons tiene una visión crítica de la deuda pública. Cuando se emite como sustituto del dinero, puede surgir inflación si se daña la confianza de los inversores. El dinero no se gestiona fácilmente junto con la deuda (este tipo de constitución monetaria también lo concibe Irving Fisher, quien, como economista puro, no se detiene en la visión filosófica que es la raíz del pensamiento de Simons). 142

Con referencia al segundo objetivo, la regulación del mercado, el mayor enemigo de una democracia liberal es el monopolio, ya sea en forma de grandes corporaciones, cárteles industriales, agencias de control de precios, o también sindicatos. De hecho, el mejor criterio de eficiencia económica es el sistema de precios. Los precios deben determinarse libremente en cualquier mercado (incluido el mercado laboral): el resultado de compras competitivas por personas libres de utilizar el poder adquisitivo como les plazca. Por lo tanto, Simons es crítico con los sindicatos, porque a través de la negociación colectiva, intentan elevar el nivel de los salarios por encima del nivel determinado por la competencia, reduciendo así las oportunidades de empleo.

La mitigación de las desigualdades, este es su tercer punto, es incompatible con la eficiencia económica. Es cierto que, como consecuencia de un sistema de precios de libre mercado (incluidos los salarios), los individuos se encuentran en circunstancias de ingresos muy diferentes, pero los "problemas de ineficiencia y desigualdad ... son, dentro de límites bastante amplios, distintos e independientes" . 143 La desigualdad es un problema aparte que debe resolverse mediante impuestos progresivos.

Como se mencionó anteriormente, Simons es muy crítico con ese tipo de liberales que ven un papel activo del Estado en la economía, a quienes llama “colectivistas”. Al revisar sus libros, ataca tanto al keynesiano Alvin Hansen como, aún más, a William Beveridge. Refiriéndose a su Pleno empleo en una sociedad libre , Simons escribe que "está escrito por un liberal nominal, radical-reaccionario en sus propuestas sustantivas, libertario en su retórica", y se queja de que el libro "puede pronosticar o determinar en gran medida el curso de Política británica de posguerra ”. Es filosofía política más que economía. Recordando las libertades fundamentales de Beveridge (ver arriba, Sección  3), Simons los compara con la política económica nazi e irónicamente los define como “Una cruzada contra la miseria, la enfermedad, la miseria y la ignorancia, lo cual es bueno si te gusta el esquema alemán de antes de la guerra como forma de vida nacional”; una planificación colectivista donde no hay nada que imponga la competencia. El trabajo de Beveridge no es más que un “esquema hiperkeynesiano de economía estrictamente reglamentada y nacionalismo económico extremo”. 144

Desde la perspectiva fiscal y monetaria, la crítica de Simons se dirige a la discrecionalidad otorgada al banco central: todo el poder —el de emisión y de endeudamiento— debe concentrarse en el Tesoro. El Tesoro, a su vez, debe asegurar la estabilidad monetaria bajo reglas definidas y coherentes, con una mínima intervención en los mercados.

Este punto de vista radical y libertario no podría ser aceptado acríticamente ni siquiera por un economista liberal como Lionel Robbins quien, no muchos años después, escribirá: “La conveniencia de las reglas en lugar de las autoridades, para usar el contraste tan vívidamente planteado por Henry Simons, es absolutamente central para la posición libertaria principal ... [pero] creo que es una deficiencia del caso libertario ... que incluso cuando repudia explícitamente la superficialidad del laisse-faire extremo, tiende a sugerir una concepción de gobierno que está demasiado limitada a la ejecución de leyes conocidas, con exclusión de funciones de iniciativa y discreción que no pueden quedar fuera del cuadro sin distorsión ”. Y cita “el ámbito de las finanzas”: “Seguramente sería imprudente… asumir que no puede surgir ninguna situación que no pueda ser tratada por mecanismos puramente automáticos”.145

¿Qué ha agregado la “Nueva Escuela” de Chicago a la filosofía de Simons? No mucho, aparte de un mayor acento en el "liberismo". Según su principal exponente, Milton Friedman, “el gobierno es fundamental tanto como foro para determinar las 'reglas del juego' como árbitro para interpretar y hacer cumplir las reglas decididas”. 146Si comparamos las ideas de Simons y Friedman, podemos encontrar similitudes y diferencias. Sobre el problema de la distribución de la riqueza, Friedman está de acuerdo con Simons en el principio de que todo el mundo debería recibir una remuneración proporcional a su contribución al proceso de producción, salvo cualquier forma de igualitarismo. Sin embargo, Friedman se opone a los impuestos con tasas progresivas como instrumento de redistribución de la riqueza (“Me resulta difícil, como liberal, ver alguna justificación para la imposición gradual únicamente para redistribuir la renta”), prefiriendo un impuesto de tasa plana. Las elevadas tasas impositivas nominales parecen “un caso claro de utilizar la coacción para tomar de unos con el fin de dar a otros y así entrar en conflicto frontalmente con la libertad individual”. 147

En cuanto a la competencia, la función de árbitro del Estado significa que debe evitar que se confunda competencia con libertad de colusión: no se puede dejar fuera del mercado a ningún competidor que no sea vendiendo un mejor producto al mismo precio o el mismo producto a un precio más económico. (mientras que en la tradición "continental", observa, la libertad de empresa significa que las empresas son libres de fijar precios, no de competir en el mismo mercado o de adoptar prácticas para mantener fuera a los competidores potenciales). Pero cuando el monopolio tiene que ser el resultado final como la solución técnicamente más eficiente y hay tres posibles alternativas disponibles: monopolio público, monopolio privado, regulación pública del mercado de un bien o servicio específico, Friedman, aunque reacia, prefiere el monopolio privado.148 (que preferiría un mercado regulado públicamente). La motivación de Friedman es que la tecnología en rápida evolución podría permitir pasar del monopolio privado a una situación de competencia, mientras que el monopolio público, una vez establecido, sería más difícil de desmantelar. 149

La constitución monetaria de Simons toma con Friedman un carácter más definido. Él piensa que el patrón oro, nunca promulgado completamente en su automatismo implícito y, de hecho, sujeto a la discreción de los gobiernos, no es más adecuado para las condiciones actuales, pero aún más inadecuado es otorgar responsabilidades monetarias y amplios poderes discrecionales a un grupo. de tecnócratas, reunidos en un banco central independiente: un arreglo que solo ha traído inestabilidad, medida por las fluctuaciones en el stock de dinero, los precios o la producción. Un liberal tiene miedo de tal concentración de poder. Reglas en lugar de discreción:150 Estas reglas no deberían abordar un nivel óptimo de precios, lo que dejaría demasiadas maniobras discrecionales a las autoridades, sino el stock de dinero, que debería crecer en un porcentaje estable, cuantificado por Friedman en alrededor del 3-5% anual. 151

Y aquí está la motivación subyacente de su desapego de Simons: "Muchos liberales anteriores ... escribiendo en un momento en que el gobierno era pequeño para el estándar actual, estaban dispuestos a que el gobierno emprendiera actividades que los liberales de hoy no aceptarían ahora que el gobierno se ha vuelto tan desbordado" . 152

## Ordoliberalismo o liberalismo autoritario {-}

El papel del Estado en el esquema ordoliberal es suficiente para distinguir a los ordoliberales alemanes de Hayek y los “austriacos” en general. A primera vista, todos ellos podrían verse como muy similares a los ordoliberales, y ciertamente existía un vínculo de simpatía entre ellos, ligado como estaban por su confianza compartida en la eficiencia de los mercados, en el sistema de precios como indicador de valor de los productos y factores de producción, en la libertad de entrada al mercado y en el énfasis en las opciones individuales. Pero, como veremos, hay diferencias. Estas diferencias enfatizan las peculiaridades de los ordoliberales no solo en relación con los austriacos, sino también con la nueva Escuela de Chicago, reacia a reconocer el papel central del Estado en la economía.

En definitiva, la visión de los ordoliberales se basa en el reconocimiento de la fuerza del Estado en el centro mismo del sistema económico. Su enfoque es coherente con el enfoque intelectual específicamente alemán que intentamos resumir con cierta extensión en el Capítulo 1. (Secs. 6-10), y es un reconocimiento explícito del amplio papel que definitivamente estaba asumiendo el Estado en el gobierno de las economías nacionales en el siglo XX. Es oportuno agregar que, de manera similar a la Escuela Histórica Alemana, el enfoque ordoliberal no puede ser estudiado como una especie de “modelo”, en el sentido que un economista podría atribuir a esta palabra; es más bien un esquema esencialmente prescriptivo sobre la estructura y organización del sistema económico, dentro de un marco político bien definido. Este enfoque requiere una conexión estricta entre economía y derecho: se enfatiza con especial énfasis que el marco legal de un sistema económico debe construirse cuidadosamente, siendo esencial para su correcto funcionamiento.

Se puede plantear un interrogante acerca de si el ordoliberalismo debe incluirse dentro de una definición amplia de liberalismo o si debe estar conectado a un nacionalismo autoritario. Lo que hay que señalar al comienzo de esta sección es que el ordoliberalismo no puede verse como un monolito: algunos ordoliberales centran su atención en un Estado omnipotente (“El Leviatán estaba y tenía que estar allí” 153 ), otros en la eficiencia de los mercados libres. Un corolario del primer rasgo es el poder abrumador del Estado para dictar leyes en el interés superior de toda la nación, como lo prevén los gobernantes, y el papel político mínimo atribuido a los individuos, como entidades no politizadas que simplemente tienen que buscar su bien. -ser sin suplicar el apoyo del Estado.

Para entender el ordoliberalismo, acabamos de hacer una referencia al marco intelectual alemán, y aquí viene a la mente el nombre de Carl Schmitt. Schmitt fue un jurista destacado y, si bien no es nuestra intención detenernos en sus pensamientos sobre la disciplina del derecho y el papel del Estado, un hecho que no puede pasarse por alto es que fue un ideólogo y experto constitucional del Estado nazi. Compartió con los primeros ordoliberales el disgusto por la democracia liberal, poniendo más bien énfasis en una visión peculiar y aparentemente contradictoria de un Estado liberal-autoritario, que protege al mercado de las solicitudes de redistribución de la riqueza.

Algunas palabras sobre Schmitt son necesarias, porque su forma de razonar está muy cerca de los primeros pensadores ordoliberales. 154Distingue el "Estado total", encarnado por la República de Weimar, y el Estado "autoritario". Aquí, "total" significa una democracia pluralista, donde la representación parlamentaria refleja una homogeneidad de gobernantes y gobernados, y ya no se centra en los intereses burgueses; mientras que el gobierno es responsable de las emociones y pasiones masivas. La República de Weimar es vista críticamente como el emblema de la crisis de una sociedad de masas desenfrenada en rebelión, que de hecho había “suplantado al Estado liberal”. Demasiado Estado democrático había significado una sobrecarga política y económica excesiva, y de esta manera una contradicción efectiva de los principios liberales. Una línea de separación entre Estado y sociedad resultaría útil para ambos: por un lado, significaría una capacidad efectiva del Estado para gobernar, y por otro, un libre ejercicio de la fuerza de trabajo por parte de todas las personas económicamente activas, donde todos serían tratados por igual en virtud del Estado de derecho. La tarea del Estado es liberar la economía despolitizando las relaciones socioeconómicas. El Estado no debe ser el objetivo de los trabajadores que buscan el bienestar; Los proletarios rebeldes deben transformarse en ejercitantes independientes y dispuestos de su propia fuerza de trabajo: este es “el heroísmo de la pobreza, el sacrificio y la disciplina”. En resumen, una economía libre no es un orden natural, sino el resultado de una práctica gubernamental. El Estado es la categoría predominante de economía política. Los proletarios rebeldes deben transformarse en ejercitantes independientes y dispuestos de su propia fuerza de trabajo: este es “el heroísmo de la pobreza, el sacrificio y la disciplina”. En resumen, una economía libre no es un orden natural, sino el resultado de una práctica gubernamental. El Estado es la categoría predominante de economía política. Los proletarios rebeldes deben transformarse en ejercitantes independientes y dispuestos de su propia fuerza de trabajo: este es “el heroísmo de la pobreza, el sacrificio y la disciplina”. En resumen, una economía libre no es un orden natural, sino el resultado de una práctica gubernamental. El Estado es la categoría predominante de economía política.

Por tanto, era necesario, según Schmitt, restaurar el Estado como una institución independiente de toma de decisiones autorizada (independiente de la sociedad de masas). En épocas anormales, como las vividas bajo Weimar, no sería posible una democracia real.

En un discurso de noviembre de 1932, en las etapas finales de la República de Weimar, titulado Estado fuerte y economía sana, Schmitt sostiene que en el siglo XX todos los estados tienden a volverse "totales", pero Weimar era un "estado total cuantitativo", incapaz de resistir presiones provenientes de partidos y partidos contrarios; el Estado total que se necesita es de tipo “cualitativo”, con control sobre el ejército y la burocracia, mientras que otras áreas se dejan a la autogestión y a la economía libre: un nuevo orden, potencialmente corporativista y autoritario, para preservar la propiedad, pero al mismo tiempo, y de manera un tanto contradictoria, un orden que defendería los derechos liberales tradicionales del hombre frente al Estado, así como defendería al Estado frente a la amenaza de la democracia liberal: una democracia despolitizada, con un marginado parlamento.155

Al comienzo mismo del Tercer Reich, escribe que la nueva Ley de Habilitación de 1933, que marca el comienzo del Reich de Hitler, aunque se presenta formalmente como un cambio a la anterior constitución de Weimar, débil y "neutral", representa un cambio radical: la ley ha ha sido decidido por el parlamento sólo en obediencia a la voluntad del pueblo expresada en las elecciones políticas que se acaban de celebrar; en realidad es un referéndum popular, un plebiscito, que reconoce a Hitler como líder político del pueblo alemán. Se abolieron la libertad de propaganda, opinión, conciencia y actividad, y la neutralidad ideológica de la constitución de Weimar. Esa constitución “de ninguna manera fue capaz de reconocer ni siquiera a un enemigo mortal del pueblo alemán para abolir al Partido Comunista, enemigo del Estado y del pueblo”. 4 de este ensayo.

En cuanto al Estado, Schmitt afirma una unidad fundamental del cuerpo político, que es el resultado de tres estructuras: el Estado mismo, el Movimiento y el Pueblo. No están en posiciones paralelas: el Movimiento es la estructura dinámica y está encarnado en el partido, el partido único de los trabajadores nacionalsocialistas alemanes; sostiene a los otros dos, los penetra y los conduce. El Estado es el miembro estático de esta estructura triádica: la organización del mando, la administración y la justicia. El Pueblo es la vida social y económica de la nación, que crece al amparo y a la sombra de las decisiones políticas.

Todo el mundo liberal ha caído. Como en la Italia fascista, las calles sin salida de la democracia liberal están abandonadas. La constitución democrática liberal típica —observa Schmitt— se basaba en la oposición de dos entidades, ya fueran Estado / sociedad; o Estado / individuo; o poder del Estado / libertad individual; o política / dominio privado. Esta separación tiene por objeto separar el poder del Estado de la sociedad, de modo que esta última pueda controlar al primero, como defensa de la sociedad contra el poder del Estado. La estructura triádica alemana supera esta división. En Alemania, hasta mediados del siglo XIX, el Estado no reconoció esa división y tuvo un papel abrumador, hegeliano. Pero incluso después de eso, con el advenimiento del liberalismo y el positivismo, el Estado siguió siendo en Alemania un Estado administrativo, con su clase de funcionarios públicos que no era un instrumento, sino una fuerza independiente del propio Estado. Por tanto, la visión hegeliana se mantuvo, y escritores como Adolf Wagner y Gustav Schmoller [el principal exponente de la Escuela Histórica de Economía Alemana, véase el capítulo 1 ] mantuvo vivo ese gran concepto alemán: la conciencia de que la clase culta e incorruptible de los funcionarios públicos alemanes la hace superior a la sociedad burguesa.

Hay similitudes entre las líneas de pensamiento de Schmitt y la doctrina económica ordoliberal: la visión de Weimar como un fracaso que resulta de la intervención del Estado en la vida económica, de una sobreexpansión social y fiscal, luego seguida de una política deflacionaria y, en general, cambios económicos parciales; actitud crítica hacia la democracia de masas y preferencia por un gobierno autoritario. Schmitt y los primeros ordoliberales también mantienen la forma muy característica de ver a la clase trabajadora como formada por individuos individuales con "fuerza de trabajo libre", capaces de ejercer sus capacidades sin referencia a intereses comunes y solidaridad de clase, y por lo tanto de ver la sociedad como un conjunto. de relaciones socioeconómicas despolitizadas. Por otro lado, y de manera muy clara, los ordoliberales reaccionan contra el dirigismo,156

Según los ordoliberales, la "destrucción creativa" de los mercados, adoptada por la economía austriaca, no es suficiente para asegurar el dinamismo necesario para la economía (por ejemplo, la existencia de grandes monopolios se debe, piensa von Mises, a la interferencia del gobierno en la libertad de los mercados; por el contrario, para los ordoliberales, corresponde al gobierno resistir los monopolios creados por los mercados sin trabas). Los ordoliberales piensan que solo la autoridad del Estado puede ejercer la fuerza necesaria para crear un sistema económico eficiente (para los austriacos, este objetivo solo puede ser alcanzado por el sector privado, a través del interés propio de sus componentes). La libertad económica descansa sobre un Estado fuerte, que garantiza un equilibrio social, definido como una situación en la que el individuo está protegido contra la hegemonía de los mercados descontrolados.

El ordoliberalismo nació en el contexto de la Gran Depresión, la crisis de la República de Weimar y la dictadura nazi. Más allá de las diferencias que caracterizan a sus partidarios individuales, generalmente se considera como una forma alternativa neoliberal de economía política al liberalismo del laissez-faire y al colectivismo, en sus diversas formas. Se ha escrito que “el dicho de que la economía libre depende del estado fuerte es clave para su postura teórica”. 157 Pero, al mismo tiempo, esta relevancia atribuida al Estado está lejos de las ideas de Keynes o Beveridge: nuevamente, otra evidencia de las metamorfosis del liberalismo del siglo XX.

Los puntos centrales de la filosofía ordoliberal se pueden identificar de la siguiente manera:

> la competencia de mercado, lejos de ser espontánea, está definida y amparada por las regulaciones del Estado: un Estado fuerte, muy diferente del Estado limitado y débil del pensamiento liberal clásico;
>
> sólo en un mercado basado en la competencia, regulado y protegido por el Estado, el emprendedor puede operar, con su reconocida vitalidad y energía y liderazgo innovador: no entrará como tal en el debate político sobre las estructuras y transacciones del mercado.

El Estado debe actuar de manera que desproletarice las estructuras sociales del capitalismo. Esta desproletarización apunta a vaciar las estructuras sociales marxistas de cualquier contenido. “La solución a la condición proletaria consiste en el esfuerzo constantemente renovado por eliminar al proletariado mediante una política social acorde con el mercado que, en lugar de aprisionar a los trabajadores en el estado de bienestar, facilita su libertad y responsabilidad, haciendo a cada uno como un propietario. empresario". 158 Como se dijo anteriormente, el trabajador se integra socialmente en el proceso de producción. Mantiene firmes valores sociales y éticos, arraigados en la tradición, la familia y la comunidad. La imagen de un trabajador desproletarizado y seguro de sí mismo acerca el esquema de los ordoliberales al de Einaudi.

Todo esto representa un fuerte vuelco de la economía positiva, a favor de la economía prescriptiva: el problema no es desarrollar un modelo analítico para explicar el mundo real, sino cambiar el mundo real haciéndolo coherente con el modelo ordoliberal. Este modelo ve la autoridad política como el instrumento necesario para establecer un sistema económico libre.

En 1936 se publicó en Alemania un Manifiesto Ordoliberal , firmado por Franz Böhm, Walter Euken y Hans Grossman Dörth. 159 Según una orientación profundamente arraigada de la tradición intelectual alemana (véase el capítulo 1 ), los autores abordan las disciplinas tanto del derecho como de la economía pero, separándose de la Escuela Histórica, piensan que estas dos disciplinas fueron efectivamente desatendidas durante los siglos XIX y XX. Esta negligencia se debió de hecho a la prevalencia del historicismo: por un lado, había observado correctamente, en contra de las ideas de la Ilustración, que en realidad no existe ningún sistema natural de derecho y economía (como lo subraya completa y correctamente List, en el campo de economía, y Savigny, en el campo del derecho). Pero, apoyarse en el historicismo había expuesto esas disciplinas al riesgo de extinción, por su relativismo y fatalismo.

El relativismo está implícito en la afirmación de que el derecho debe ser desarrollado por las "fuerzas internas silenciosas" de la sociedad, no a discreción del legislador: la sustancia del derecho surge de desarrollos históricos y leyes hechas por juristas, que también gobiernan las relaciones económicas. De esta manera, gracias a este enfoque, “el capitalismo siempre ha encontrado formas y medios para triunfar de lege, praeter legem et contra legem ”. De hecho, si los engendradores del derecho son esas "fuerzas silenciosas internas", si el derecho es generado por la sociedad misma y no por la voluntad del legislador, el derecho mismo no puede reaccionar contra esas fuerzas (por ejemplo, esta concepción de una especie de El poder creativo de los jueces no impidió la creación de grandes carteles industriales, es decir, la negación de un mercado eficiente y competitivo).

Los ordoliberales ven los trabajos de economistas de la Escuela Histórica de Economía Alemana como ejercicios de relativismo, también desde un punto de vista metodológico. Fracasaron por su empirismo, que consiste en observar y recopilar una enorme cantidad de hechos sin notar sus interdependencias. La realidad económica, de hecho, no puede entenderse si se la considera como una masa de eventos no correlacionados. Su relativismo les impidió utilizar la economía política clásica tal como se construyó durante el siglo XIX. Ellos “no sabían cómo utilizar el aparato de pensamiento abstracto de la economía política” y les era “imposible llegar a una comprensión de las interdependencias dentro del sistema económico”. 160 Terminaron en una confianza en el progreso, de sabor hegeliano, justificada por la fe, no sustentada en un esquema lógico.

El fatalismo —observan los autores del Manifiesto de Ordo— es común a escritores tan diversos como Marx y Spengler, el primero determinista, el segundo escéptico: según ambos, las cosas no se pueden cambiar, solo se pueden observar. El conjunto de la vida social, política e intelectual no puede verse como otra cosa que una “superestructura”, superpuesta a una estructura que evoluciona según sus propias leyes, las “fuerzas silenciosas internas” mencionadas anteriormente.

El programa de los ordoliberales tiene como objetivo la construcción y organización de un sistema económico basado en una serie de principios 161 :

> Adoptar una actitud científica en el estudio del derecho y la economía.
>
> yendo más allá del relativismo del historicismo
>
> al mismo tiempo, reconociendo la importancia de la evidencia histórica
>
> comprender la constitución (estructura) de la economía para decidir cómo se debe reorganizar la actividad económica a través de la legislación. En este sentido, el problema de comprender y diseñar los instrumentos legales necesarios para una constitución económica sólo puede resolverse si el legislador se vale de los hallazgos de la investigación económica.

El pensamiento ordoliberal parte, por tanto, de una crítica tanto del sistema “natural” en el que se basa la economía clásica como del determinismo historicista, pero acaba por injertar la economía clásica en el árbol del historicismo alemán. Esto quiere decir que toma de ambos lo que se considera convincente en sus aportaciones.

Las opiniones expresadas en los aportes de los ordoliberales no son unánimes: algunos insisten en el papel central del Estado, otros en la eficiencia de un mercado libre y competitivo. Estas diferentes visiones nos devuelven a las dos raíces del pensamiento económico que hemos tratado de describir, siguiendo los pasos de Schumpeter, en el capítulo 1. : uno basado en el individuo, alimentado por la filosofía de la Ilustración, y el otro centrado en el Estado, tal como lo definieron históricamente y lo describieron los filósofos alemanes. Los ordoliberales se basan en ambas visiones, pero prevalece la segunda visión. Probablemente esto se deba al hecho de que el renacimiento del liberalismo en Alemania tiene lugar en los años que preceden y siguen a la Segunda Guerra Mundial, y en Alemania las tradiciones de la disciplina de la economía habían ido en una dirección opuesta a la del liberalismo. de la doctrina económica clásica. No por casualidad, Gustav Schmoller había ignorado esta doctrina como “economía de los vendedores ambulantes”. 162 Aunque el ordoliberalismo era crítico con la Escuela Histórica, como hemos visto, los ordoliberales estaban condicionados por ese mismo historicismo, y el papel del Estado era mucho mayor que en la doctrina clásica.

La tradición historicista y estatista es claramente visible en los escritos de Euken. Probablemente en ninguna parte más que en un artículo de 1948163—Donde se pregunta qué tipo de sistema económico debería construirse en la derrotada Alemania. Su enfoque es típicamente microeconómico. Euken observa que las reglas que rigen los sistemas económicos de los países industrializados deberían obtener idealmente los mismos resultados que los obtenidos en una pequeña economía de subsistencia cerrada. Cualquiera que gobierne esta pequeña economía debe tener un conocimiento detallado de lo que está sucediendo en toda la economía y ser capaz de evaluar su utilidad. También debería poder dar instrucciones sobre la forma más eficiente de utilizar todos los factores de producción. Todas las interdependencias de la actividad económica en esa pequeña economía son percibidas directamente por el gobernante, que puede tomar correctamente las decisiones adecuadas. 164

De manera similar, existen interdependencias en un gran país industrializado, pero no se detectan fácilmente de manera completa y actualizada. Entonces, lo que se necesita es “alguna medida de escasez”, que indicaría qué bienes escasean y cómo se deben combinar los factores de producción para producir lo que se necesita. Este “indicador de escasez” viene dado, para las empresas y los hogares, por el sistema de precios, y sobre la base del precio los agentes económicos pueden calcular lo que se va a producir y la combinación más eficiente de los factores de producción, de una manera que sea similar a una máquina de calcular. Hasta ahora, Euken parece seguir la doctrina clásica (como lo ha vuelto a exponer, por ejemplo, Hayek). Pero, dado que los precios se determinan de manera diferente según las diferentes condiciones de los mercados en cuestión, no pueden ser un indicador de escasez en toda la economía. Las interconexiones entre los diferentes elementos de la economía hacen necesario ver cada acto de política económica en el contexto de todo el proceso económico. “Un sistema económico tiene que controlar adecuadamente todo el proceso económico de forma razonable y para ello es necesario que sus componentes individuales se complementen entre sí”.165

Sin embargo, este indicador de escasez a nivel sistémico debe diseñarse como un instrumento para hacer el sistema más eficiente, no para alcanzar el pleno empleo. De hecho, el objetivo del pleno empleo puede conducir a un empleo de mano de obra en sectores improductivos, mientras que en otros sectores pueden surgir cuellos de botella como consecuencia de la escasez de factores de producción disponibles. Las inversiones deben elegirse bajo el control del Estado en la proporción correcta, en todos los sectores, industrias o incluso regiones o empresas específicas. El control de todo el proceso de producción y, a través de él, la consecución del pleno empleo, es una política sabia; no así una política que busque a priori un pleno empleo que enmascare o ignore el tema de la eficiencia. El Estado ordoliberal es un planificador, no con fines sociales sino para evitar el mal funcionamiento del mercado.166

En este esquema, la política fiscal está al margen: no hay espacio para ella, es decir, para fines keynesianos o de “finanzas funcionales”. En un orden liberal perfecto, no hay necesidad de políticas de estabilización porque la actividad económica es estable por definición. 167 Por lo tanto, Euken no considera el uso de la política fiscal para fines de gestión de la demanda tanto en recesiones cíclicas como en el caso de problemas estructurales: incluso en este último caso, solo se necesitan reformas estructurales, operando del lado de la oferta de la economía, que es haciendo que la oferta sea más eficiente, no gestionando la demanda. 168

Si miramos la relación entre el sistema fiscal y el sistema económico, hay una diferencia notable entre la taxonomía de Beveridge, que implica un papel activo y funcional otorgado al primero, y la taxonomía aséptica adelantada, unos años después, por un ordoliberal. escritor, Kurt Schmidt, 169 donde no se prevé un vínculo entre la política presupuestaria pública y el empleo y, más aún, no se menciona el uso de la deuda pública para promoverla.

Los ordoliberales muestran igual renuencia a apoyar un papel activo de la política monetaria. En este sentido, los primeros ordoliberales expresaron, no por casualidad, una clara preferencia por el patrón oro. Friedrich Lutz, en un artículo que se remonta a 1935, 170escrito durante los últimos suspiros del antiguo régimen monetario, sigue destacando las ventajas de un sistema de tipos de cambio fijos, de contención del stock de dinero dentro de los límites de la reserva de oro, de una distribución internacional de las reservas de oro en relación con la evolución de la balanza de pagos, y de un mecanismo automático basado en unas pocas reglas de juego precisas, donde no se deja absolutamente nada a la gestión de los bancos centrales. El buen funcionamiento de este sistema implica la exclusión de las políticas monetarias independientes, ligadas a las condiciones específicas del ciclo económico, y del proteccionismo. Lutz reconoce sin embargo la profunda crisis del patrón oro: la pérdida de oro de un determinado país con un déficit en las cuentas exteriores es seguida por una caída, difícil de aceptar social y políticamente, en salarios y precios y al final por desempleo, para recuperar competitividad. Por eso —observa— este régimen ha sido recientemente abandonado por Reino Unido y Estados Unidos (y sería abandonado al año siguiente por Italia y Francia). El éxito decisivo de las ideas nacionalistas (estamos, vale la pena repetirlo, en 1935) lleva a Lutz a preguntarse si se podría introducir un sistema monetario “controlado a nivel nacional”, como vía de escape del patrón oro. Contempla una serie de medidas técnicas para alcanzar ese objetivo, El éxito decisivo de las ideas nacionalistas (estamos, vale la pena repetirlo, en 1935) lleva a Lutz a preguntarse si se podría introducir un sistema monetario “controlado a nivel nacional”, como vía de escape del patrón oro. Contempla una serie de medidas técnicas para alcanzar ese objetivo, El éxito decisivo de las ideas nacionalistas (estamos, vale la pena repetirlo, en 1935) lleva a Lutz a preguntarse si se podría introducir un sistema monetario “controlado a nivel nacional”, como vía de escape del patrón oro. Contempla una serie de medidas técnicas para alcanzar ese objetivo,171 pero agrega que, como paso preliminar, debe resolverse el problema más general de la alternativa entre una economía libre y una economía planificada. 172Este tema no resuelto puede explicar por qué el pensamiento ordoliberal sobre política monetaria nunca fue más allá de un “monetarismo” genérico, es decir, prestar atención a mantener bajo control la base monetaria mediante reglas que excluyen la discreción, políticamente maniobrable, de los bancos centrales, para obtener dinero estable (ver Friedman, arriba). Esta posición va acompañada de una actitud escéptica sobre el uso de la política monetaria para sostener o frenar el crecimiento económico (un uso de la política monetaria que podría denominarse keynesiana) y, en cambio, de la afirmación de la neutralidad del dinero, cuya gestión activa pone en riesgo generando inestabilidad. En resumen, lo importante para los pensadores liberalistas no es la política monetaria, sino una constitución monetaria.173 Desconfían particularmente de la expansión de la oferta monetaria a través del crédito bancario, desconfianza que incluso llevó a Euken a adherirse a la Escuela de Chicago, de la que los ordoliberales estaban, en otros aspectos, principalmente el papel del Estado, bastante distantes.

Alfred Müller-Armack está más orientado hacia el neoliberalismo de la escuela austriaca y, por tanto, menos centrado en la centralidad del Estado. 174 En primer lugar, en todo caso confirma que el concepto de libre competencia tiene un papel central, no identificable con el laissez-faire porque requiere de una serie de garantías institucionales, encaminadas a prevenir restricciones comerciales y controlar monopolios, oligopolios y cárteles, para el beneficio de los consumidores. De esta manera, el sistema económico puede funcionar correctamente y realizar al mismo tiempo una función social. La competencia es un requisito previo de la libertad económica que no se puede encontrar ni generar en la esfera del sector privado.

Müller-Armack también se interesa por el Estado del Bienestar, pero en una perspectiva muy alejada de la de Beveridge. Las salvaguardias proporcionadas por el Estado de Bienestar deben mantenerse, pero cualquier intervención pública debe ser acorde con el mercado. Esto significa una mezcla de libertad de mercado y equilibrio social: una "economía social de mercado", una expresión familiarizada por las políticas del gobierno alemán, particularmente cuando Ludwig Erhard era ministro de Economía (1949-1963). Al respecto, se reconoce que es deber del Estado intervenir en la redistribución de la producción -a través del sistema estatal de pensiones, seguros sociales y diversos subsidios a las clases menos acomodadas- pero el gasto social no debe sobrepasar el umbral en que obstaculizaría el funcionamiento del mercado competitivo y la producción de ingresos. Respecto a la fiscalidad, Cumplir con el mismo principio significaría que tasas impositivas demasiado altas, diseñadas para financiar el gasto social, dañarían la producción de ingresos. En un mercado que funcione correctamente, escribe, la creación de nueva riqueza sería suficiente y capaz de tolerar una redistribución considerable de la riqueza sin un aumento excesivo de las tasas impositivas. Una vez más, no se le da ningún papel al financiamiento del déficit público con el propósito de redistribuirlo.

Wilhelm Röpke desarrolla más este tema: la "libertad de la necesidad" de Roosevelt es "un concepto negativo", porque significa que los necesitados tienen que depender de los demás, es decir, de tomar de los demás, para su propio sustento. Esto también significa que el Estado debe usar su poder de coerción para obligar a otros a sostener a los necesitados. Pero si la fiscalidad alcanza niveles excesivos, los recursos disponibles se agotan, en perjuicio de todos. En una sociedad libre, el mismo objetivo debe perseguirse principalmente de forma voluntaria, a través del ahorro, los seguros y las contribuciones voluntarias. Sólo así se superará la “forma de existencia proletaria”. 175En la misma línea, Müller-Armack piensa que mantener los tipos de interés artificialmente bajos para facilitar el crédito a los deudores desfavorecidos no es coherente con el mercado, así como congelar las rentas en todo el mercado inmobiliario sin tener en cuenta el grado en que los arrendatarios pueden pagar las rentas, mientras que un sistema de rentas subvencionadas solo para los pobres sería compatible con el mercado. 176

El énfasis puesto por los ordoliberales en los temas políticos en un sentido amplio ha suscitado la pregunta: ¿qué nuevas ideas han aportado a la teoría económica? Se ha señalado que sus temas —como la estabilidad monetaria, el mercado y su regulación, la competencia y la libertad comercial— eran conceptos ya familiares para la economía, y que “la verdadera razón [de su éxito] reside en el corazón mismo de la filosofía de la economía social de mercado… sus teóricos produjeron pocas sugerencias concretas para la prevención del crecimiento excesivo del Estado ”. 177Este es un comentario que solo puede aceptarse parcialmente. Observamos que, por un lado, no encontraremos en su trabajo, por ejemplo, ningún análisis profundo sobre las características de los diferentes tipos de mercados, ni ningún cálculo del efecto multiplicador de un determinado gasto, mientras que, por otro, Por otro lado, la economía dominante, que es analíticamente fuerte, a menudo no está interesada en el aspecto institucional, como un factor exógeno que debe darse por sentado. Los fenómenos que observan los ordoliberales son los mismos que los analizados por los economistas convencionales, pero desde un punto de vista diferente: no les interesan las regularidades legales de comportamiento que demarcan la economía como un campo de análisis social, ni en la construcción de “modelos”. Como se mencionó anteriormente, un “modelo ordoliberal” simplemente no existe. Miran el lado prescriptivo, armados con instrumentos generalmente ignorados por los economistas, como la historia y el derecho, y están más interesados ​​en una constitución económica que en una macrogestión activa de la economía (se ignora la macroeconomía). Si sus recetas fueron (son) propicias para el bienestar económico, es un tema de debate. Pero lo cierto es que “la prevención del crecimiento del Estado” encuentra en sus teorías condiciones y límites, más estructurados y argumentados que en otros análisis de economistas con diferente bagaje. Y el resultado fue una estrategia nacional del lado de la oferta que utilizó recursos culturales e institucionales tradicionales para asumir un papel principal a nivel europeo y global (como muestran claramente incluso los desarrollos actuales en Europa; pero este es un tema que se tratará más adelante en este ensayo). como la historia y el derecho, y están más interesados ​​en una constitución económica que en una macrogestión activa de la economía (se ignora la macroeconomía). Si sus recetas fueron (son) propicias para el bienestar económico, es un tema de debate. Pero lo cierto es que “la prevención del crecimiento del Estado” encuentra en sus teorías condiciones y límites, más estructurados y argumentados que en otros análisis de economistas con diferente bagaje. Y el resultado fue una estrategia nacional del lado de la oferta que utilizó recursos culturales e institucionales tradicionales para asumir un papel principal a nivel europeo y global (como muestran claramente incluso los desarrollos actuales en Europa; pero este es un tema que se tratará más adelante en este ensayo). como la historia y el derecho, y están más interesados ​​en una constitución económica que en una macrogestión activa de la economía (se ignora la macroeconomía). Si sus recetas fueron (son) propicias para el bienestar económico, es un tema de debate. Pero lo cierto es que “la prevención del crecimiento del Estado” encuentra en sus teorías condiciones y límites, más estructurados y argumentados que en otros análisis de economistas con diferente bagaje. Y el resultado fue una estrategia nacional del lado de la oferta que utilizó recursos culturales e institucionales tradicionales para asumir un papel principal a nivel europeo y global (como muestran claramente incluso los desarrollos actuales en Europa; pero este es un tema que se tratará más adelante en este ensayo). y están más interesados ​​en una constitución económica que en una macrogestión activa de la economía (se ignora la macroeconomía). Si sus recetas fueron (son) propicias para el bienestar económico, es un tema de debate. Pero lo cierto es que “la prevención del crecimiento del Estado” encuentra en sus teorías condiciones y límites, más estructurados y argumentados que en otros análisis de economistas con diferente bagaje. Y el resultado fue una estrategia nacional del lado de la oferta que utilizó recursos culturales e institucionales tradicionales para asumir un papel principal a nivel europeo y global (como muestran claramente incluso los desarrollos actuales en Europa; pero este es un tema que se tratará más adelante en este ensayo). y están más interesados ​​en una constitución económica que en una macrogestión activa de la economía (se ignora la macroeconomía). Si sus recetas fueron (son) propicias para el bienestar económico, es un tema de debate. Pero lo cierto es que “la prevención del crecimiento del Estado” encuentra en sus teorías condiciones y límites, más estructurados y argumentados que en otros análisis de economistas con diferente bagaje. Y el resultado fue una estrategia nacional del lado de la oferta que utilizó recursos culturales e institucionales tradicionales para asumir un papel principal a nivel europeo y global (como muestran claramente incluso los desarrollos actuales en Europa; pero este es un tema que se tratará más adelante en este ensayo). Pero lo cierto es que “la prevención del crecimiento del Estado” encuentra en sus teorías condiciones y límites, más estructurados y argumentados que en otros análisis de economistas con diferente bagaje. Y el resultado fue una estrategia nacional del lado de la oferta que utilizó recursos culturales e institucionales tradicionales para asumir un papel principal a nivel europeo y global (como muestran claramente incluso los desarrollos actuales en Europa; pero este es un tema que se tratará más adelante en este ensayo). Pero lo cierto es que “la prevención del crecimiento del Estado” encuentra en sus teorías condiciones y límites, más estructurados y argumentados que en otros análisis de economistas con diferente bagaje. Y el resultado fue una estrategia nacional del lado de la oferta que utilizó recursos culturales e institucionales tradicionales para asumir un papel principal a nivel europeo y global (como muestran claramente incluso los desarrollos actuales en Europa; pero este es un tema que se tratará más adelante en este ensayo).

Notas
1.
Baffigi2009, pag. 8).

 
2.
Si nos centramos principalmente en su origen.

 
3.
"Cuando los hechos cambian, cambio de opinión", dijo Keynes, según se informa.

 
4.
Keynes (1926, págs. 14-15).

 
5.
Joan Robinson afirmaría entonces que con Keynes “la economía volvió a convertirse en economía política”.

 
6.
Skidelsky1992, pag. 224).

 
7.
Trevelyan1944, pag. 557).

 
8.
Stein1990, pag. 6).

 
9.
Esta sociedad, que existe desde finales del siglo XIX, tomó su nombre del romano Quintus Fabius Maximus, el cunctator , que es el general de movimiento lento pero tenaz. Sería un símbolo del inexorable, aunque gradual, movimiento hacia el socialismo, en contraposición a la estrategia diversa, de cambios revolucionarios repentinos.

 
10.
90 liras por libra británica, muy por encima de la tasa de mercado imperante que había llegado a 125 liras por libra.

 
11.
Blackett1932, pag. 96).

 
12.
Croce1973).

 
13.
A diferencia de la "Filosofía del Espíritu", en la que no nos detendremos.

 
14.
Croce1973, pag. 286). Joan Robinson definió el valor como “una idea metafísica”; con la identificación del valor con el producto del trabajo (Ricardo, y luego Marx), la idea metafísica, dice Robinson, se convierte en una "hipótesis" (1974, págs. 29-30).

 
15.
Al menos en un caso tenemos evidencia de una relación entre los dos: Keynes encargó a Croce un artículo para su serie de informes sobre Reconstrucción en Europa, para el Manchester Guardian, en 1922: La visión de la población de un filósofo. Ver Kelly (2019).

 
dieciséis.
Croce1973, pag. 301).

 
17.
Bodei (2003).

 
18.
Schumpeter, en una línea similar, cuestionó si la competencia perfecta es una construcción teórica o una realidad histórica (1947, pag. 107).

 
19.
En este texto, me atengo, en su caso, a la traducción literal de la palabra italiana como neologismo en inglés.

 
20.
Croce1973, pag. 264). Sin embargo, podríamos seguir el enfoque de Croce y ver la doctrina económica de Adam Smith como "ética", porque, en las circunstancias históricas de la Escocia de Smith (ese momento y lugar), estaba perfectamente en sintonía con la búsqueda de un sistema económico que definitivamente libraría a ese país. de las prácticas comerciales feudales anteriores.

 
21.
págs. 259 y 264.

 
22.
págs. 255, 256, 257.

 
23.
pag. 260.

 
24.
págs. 262-266.

 
25.
“Los economistas que emplean métodos cuantitativos, embrujados por la evidencia de sus procedimientos y no conscientes de que la suya es una evidencia nula, en lugar de limitarse a la construcción de sus esquemas muy útiles, aumentan la confusión filosofando de manera extravagante: como nosotros puede verlo en uno de los economistas más astutos y eruditos de nuestro tiempo ”Pareto (p. 287).

 
26.
“Liberista”, adjetivo de “Liberismo”, “liberalismo económico”.

 
27.
Croce2015, págs. 298-302) [publicado originalmente como ensayo único, 1927].

 
28.
pag. 303.

 
29.
Montesano2003).

 
30.
Luego hablará explícitamente de "nacionalismo" Croce (1955, pag. 283).

 
31.
págs. 284-285 y 288.

 
32.
Croce1941, pag. 163).

 
33.
El verso es del poema "I sepolcri" de Ugo Foscolo, donde escribe que Maquiavelo mostró las terribles consecuencias del poder absoluto y desenfrenado del Príncipe. Lo mismo hizo Marx —escribe Croce— al mostrar las consecuencias de la ganancia capitalista.

 
34.
Rathenau1919, pag. 62). Rathenau, copropietario y presidente de AEG, había sido director de la oficina alemana de Material de Guerra, en el Ministerio de Guerra durante la Primera Guerra Mundial. Luego sería nombrado secretario de Relaciones Exteriores de la República de Weimar, hasta su asesinato en 1922.

 
35.
pag. 20.

 
36.
pag. 54.

 
37.
pag. 85.

 
38.
pag. 64.

 
39.
págs. 68-69.

 
40.
págs. 62-87.

 
41.
Einaudi1918, págs.450-456).

 
42.
Einaudi y col. (2006, págs.5 y 7).

 
43.
Einaudi1972, pag. 6).

 
44.
Einaudi, Lezioni (1964, págs.66-81). Véase también Baffigi, págs. 25-37.

 
45.
Instituto de Nuevo Pensamiento Económico. La tradición italiana , www.hetwebsite.net/net/schools/italian.htm .

 
46.
Einaudi y col. (2006, pag. 17).

 
47.
Robinson1974, pag. 72).

 
48.
El economista (2016).

 
49.
Pigou2013, pag. 127).

 
50.
Citando a Edwin Cannan.

 
51.
pag. 128.

 
52.
Aslanbeigui, Oakes: Introducción: Reclamar a un maestro olvidado (Pigou, La economía del bienestar ).

 
53.
pag. XIV.

 
54.
Vea la Parte II. Sobre el dividendo nacional, Pigou sigue a Marshall y critica a Irving Fisher. Sobre este tema, Keynes cita a Pigou y lo explica en términos más claros (1936, pag. 38).

 
55.
Vea la Parte II, Capítulos 1 y 2.

 
56.
págs. 127-130.

 
57.
págs. 134-135.

 
58.
Hartford2018). Hartford agrega: “el economista William Nordhaus ha estimado que durante la segunda mitad del siglo XX, las empresas innovadoras generalmente lograron capturar como ganancias solo el 3.7% del valor social que crearon; el otro 96,3% se destinó a otros, mayoritariamente consumidores. Por ejemplo, la penicilina salva la vida por unos centavos ”. Si este discurso puede ser válido para las redes sociales, es discutible (ver Capítulo 4 ). 

 
59.
Pigou2013, pag. 192).

 
60.
pag. 5.

 
61.
Macmillan, 1949 [1937].

 
62.
pag. V.

 
63.
págs. 15-16. Sobre la distribución, le indigna que el 1% de las personas mayores de 25 años posea el 60% del capital total (p. 13).

 
64.
Esto recuerda, por ejemplo, la nacionalización de la energía eléctrica en Italia en la década de 1960.

 
sesenta y cinco.
Robinson1974).

 
66.
pag. 73.

 
67.
pag. 80.

 
68.
JMK a R. Harrod, 16 de julio de 1938 (1973, págs.299-300).

 
69.
Keynes (1949, págs.96 y 98).

 
70.
Keynes (1925).

 
71.
Keynes (1933) (Hitler acababa de tomar el poder).

 
72.
Keynes (1926, págs.28-29).

 
73.
Sobre Schumpeter, consulte el Capítulo 3.

 
74.
Keynes (1964, págs.339-40).

 
75.
Heibroner, Milberg (1995, pag. 31).

 
76.
Según Joan Robinson (1974, pag. sesenta y cinco).

 
77.
Skidelsky2018, pag. 386).

 
78.
Jones (2013).

 
79.
Notas finales sobre la filosofía social hacia la que podría conducir la teoría general. Es el capítulo 24 de la Teoría general del empleo, el interés y el dinero.

 
80.
Capítulo 3: El principio de la demanda efectiva.

 
81.
pag. 372.

 
82.
pag. 30.

 
83.
pag. 373.

 
84.
pag. 374.

 
85.
pág 136

 
86.
pag. 376.

 
87.
págs. 183-184.

 
88.
pag. 381.

 
89.
pag. 379.

 
90.
Hoerber2017, Capítulo 7).

 
91.
pag. 348.

 
92.
pag. 339.

 
93.
Hawtrey (1931, pag. 102).

 
94.
Steil (2013).

 
95.
Beveridge (1944, págs. 22-23).

 
96.
Ver Beveridge (1942).

 
97.
Beveridge (1944, pag. 147).

 
98.
pag. 135 . Pleno empleo se publicó en 1944, teniendo muy en cuenta la estructura y metodología de un presupuesto de guerra.

 
99.
Consulte la Parte IV y el Apéndice C de Pleno empleo, por Nicholas Kaldor.

 
100.
Beveridge (1944) Parte IV, secc. 2

 
101.
Beveridge (1944, pag. 148). Se tiene en cuenta la “eutanasia del rentista”, mencionada por Keynes.

 
102.
Lerner1944); (1951).

 
103.
Macmillan, 1946.

 
104.
Lerner1946, págs. 1-4).

 
105.
Conferencia de Halley Stewart de 1931.

 
106.
pag. 80.

 
107.
págs. 168-169.

 
108.
Hayek2008, pag. 71).

 
109.
En realidad nació en Galicia, ahora Polonia, pero entonces (1840) formaba parte del Imperio Austriaco.

 
110.
Una de sus principales obras es (1976).

 
111.
Por esta razón, la acusación de Schmoller contra él como economista clásico fue mal dirigida.

 
112.
Hayek, FA: Introducción a los principios económicos de Carl Menger , p. 13.

 
113.
El trabajo de Menger fue descartado por Schmoller como “meramente austríaco” (!). Yagi1997).

 
114.
Klein, P: Prólogo a los principios de Menger , p. 7.

 
115.
Esto recuerda la frase atribuida a Joan Robinson: “No estoy entrenado matemáticamente, luego tengo que pensar”.

 
116.
Hayek1955, pag. 203).

 
117.
págs. 189-196.

 
118.
Hayek1945). Véase también lo citado anteriormente The Counter - Revolution in Science, 1955.

 
119.
Hayek1944).

 
120.
pag. 38.

 
121.
pag. 89.

 
122.
Consulte la Introducción a la edición de Routledge de 2008, editada por Bruce Caldwell.

 
123.
pag. 13.

 
124.
pag. sesenta y cinco.

 
125.
Véase Bentham, más arriba (Capítulo 1 ). 

 
126.
pag. 13.

 
127.
pag. 73.

 
128.
Su libro está escrito en medio de la Guerra Mundial.

 
129.
Esta escuela jurídica otorga a las decisiones del poder judicial un predominio sobre el derecho formal, con el riesgo de poner en peligro el principio de certeza del derecho. La posibilidad de decisiones altamente voluntaristas y arbitrarias es potencialmente explotada por dictaduras.

 
130.
Sobre Schmitt, véase la Secta. 8 (ordoliberalismo).

 
131.
pag. 91.

 
132.
págs. 115-116.

 
133.
Simons1945, pag. 1). Este escrito, como otros citados aquí, se incluye en Economic Policy for a Free Society , University of Chicago Press, 1948, publicado póstumamente después de la prematura muerte de Simons.

 
134.
Un término usado por Walras en oposición a justicia distributiva (ver Capítulo 1 ). Este no es el único significado que se le da al término. Adam Smith se refiere a la justicia conmutativa como “hacer voluntariamente todo lo que podamos con decoro ser forzados a hacer” ( Teoría de los sentimientos morales , p. 334). 

 
135.
Simons1945, pag. 5).

 
136.
Simons1934, pag. 41).

 
137.
pag. 43.

 
138.
pag. 41.

 
139.
págs. 41-42.

 
140.
Simons1945, págs.15-16); (1936, pag. 79).

 
141.
Los requisitos (1936, pag. 79).

 
142.
Fisher (1935).

 
143.
Simons1934, págs.46-47).

 
144.
Simons1945).

 
145.
Robbins1963, págs.48-49).

 
146.
Friedman (mil novecientos ochenta y dos, pag. 15).

 
147.
pag. 174.

 
148.
Consulte la siguiente sección de este capítulo.

 
149.
págs. 26-28.

 
150.
pag. 51.

 
151.
págs. 53-54.

 
152.
pag. 32.

 
153.
Streek2015).

 
154.
Ver sobre este punto Bonefeld (2016).

 
155.
Caldwell2005, págs. 365-366). Caldwell se basa en un trabajo anterior de R.Cristi.

 
156.
Pavo real y Willgerodt (1989, pag. 3).

 
157.
Bonefeld (2012) ( https://eprints.whiterose.ac.uk ).

 
158.
pag. 12.

 
159.
El Manifiesto de Ordo de 1936 (Nuestra tarea), en Peacock, Willgerodt (Peacock, A. 1989).

 
160.
pag. 21.

 
161.
págs. 22-25.

 
162.
Barry (1989, pag. 106).

 
163.
Euken (1948).

 
164.
Se ha observado que “el ordoliberalismo es en el fondo un modelo microeconómico que desautoriza la política macroeconómica porque trata a los países, o incluso a toda una zona monetaria, como si fueran hogares individuales. Tiene sentido que las personas ahorren cuando están endeudadas, como lo hace el proverbial ama de casa suaba en Alemania. Pero si todas las personas recortan el gasto al mismo tiempo, el resultado puede ser un déficit en la demanda que anula los beneficios de las reformas microeconómicas. De vez en cuando es mejor romper las reglas que todos sufrir una miseria que respeta la ley ”( The Economist [2015]).

 
165.
Euken (1948, págs.28-29).

 
166.
Bonefeld (2012, pag. 5).

 
167.
Zettelmeier (2017, pag. 158).

 
168.
Euken (1951).

 
169.
Schmidt (1956).

 
170.
Lutz1935).

 
171.
Operaciones de mercado abierto por parte del banco central, adopción de un patrón de cambio de oro para "ahorrar" el uso de oro, intervenciones de tipo de cambio por parte del banco central, creación de un banco central internacional (págs. 238-240).

 
172.
pag. 241.

 
173.
Un ordoliberal como Wilhelm Röpke pidió un retorno al patrón oro (1951).

 
174.
Müller-Armack (1956).

 
175.
Röpke (1957).

 
176.
Müller-Armack (1956, págs.82-86).

 
177.
Barry (1989) pag. 121. Streek (2017).